import { env } from "cloudflare:workers";

let ready=false;
async function ensureSchema(){if(ready)return;await env.DB.prepare(`CREATE TABLE IF NOT EXISTS raw_leads (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,source_file text NOT NULL,source_sheet text DEFAULT '' NOT NULL,source_row integer DEFAULT 0 NOT NULL,client_name text DEFAULT '' NOT NULL,company_name text DEFAULT '' NOT NULL,email text DEFAULT '' NOT NULL,phone text DEFAULT '' NOT NULL,city text DEFAULT '' NOT NULL,plot_area real DEFAULT 0 NOT NULL,built_up_area_sqft real DEFAULT 0 NOT NULL,source_area_unit text DEFAULT 'SqFt' NOT NULL,products text DEFAULT '' NOT NULL,project_class text DEFAULT '' NOT NULL,claimed_enq_no text,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL)`).run();ready=true;}
const compact=(value:unknown)=>String(value??"").trim().toLowerCase().replace(/[^a-z0-9]/g,"");
const phoneKey=(value:unknown)=>String(value??"").replace(/\D/g,"").slice(-10);
const displayPhone=(value:unknown)=>{const text=String(value??"").trim();if(!text)return "";if(/e[+-]?\d+$/i.test(text)){const numeric=Number(text);return Number.isFinite(numeric)?String(Math.trunc(numeric)):text;}if(/^\+?\d+\.0+$/.test(text))return text.replace(/\.0+$/g,"");return text;};

export async function GET(){await ensureSchema();const result=await env.DB.prepare("SELECT * FROM raw_leads ORDER BY created_at DESC, id DESC LIMIT 5000").all();return Response.json({rawLeads:(result.results||[]).map((row:any)=>({id:Number(row.id),sourceFile:String(row.source_file||""),sourceSheet:String(row.source_sheet||""),sourceRow:Number(row.source_row||0),clientName:String(row.client_name||""),companyName:String(row.company_name||""),email:String(row.email||""),phone:displayPhone(row.phone),city:String(row.city||""),plotArea:Number(row.plot_area||0),builtUpArea:Number(row.built_up_area_sqft||0),areaUnit:String(row.source_area_unit||"SqFt"),products:String(row.products||""),projectClass:String(row.project_class||""),claimedEnqNo:row.claimed_enq_no?String(row.claimed_enq_no):"",createdAt:String(row.created_at||"")}))});}

export async function POST(request:Request){await ensureSchema();const body=await request.json() as {sourceFile?:string;rows?:Array<Record<string,unknown>>};if(!Array.isArray(body.rows)||!body.rows.length)return Response.json({error:"No raw lead rows were supplied."},{status:400});const existing=await env.DB.prepare("SELECT company_name,client_name,email,phone FROM raw_leads").all();const emails=new Set((existing.results||[]).map((row:any)=>compact(row.email)).filter(Boolean)),phones=new Set((existing.results||[]).map((row:any)=>phoneKey(row.phone)).filter((v:string)=>v.length>=7)),names=new Set((existing.results||[]).map((row:any)=>`${compact(row.company_name)}|${compact(row.client_name)}`));let created=0,duplicates=0;for(const [index,row] of body.rows.entries()){const companyName=String(row.companyName||"").trim(),clientName=String(row.clientName||"").trim(),email=String(row.email||"").trim(),phone=String(row.phone||"").trim(),emailKey=compact(email),mobileKey=phoneKey(phone),nameKey=`${compact(companyName)}|${compact(clientName)}`;if((emailKey&&emails.has(emailKey))||(mobileKey.length>=7&&phones.has(mobileKey))||names.has(nameKey)){duplicates++;continue;}await env.DB.prepare("INSERT INTO raw_leads (source_file,source_sheet,source_row,client_name,company_name,email,phone,city,plot_area,built_up_area_sqft,source_area_unit,products,project_class) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(String(body.sourceFile||"Uploaded workbook"),String(row.sourceSheet||""),Number(row.sourceRow||index+1),clientName,companyName,email,phone,String(row.city||""),Number(row.plotArea||0),Number(row.builtUpArea||0),String(row.areaUnit||"SqFt"),String(row.products||""),String(row.projectClass||"")).run();created++;if(emailKey)emails.add(emailKey);if(mobileKey.length>=7)phones.add(mobileKey);names.add(nameKey);}return Response.json({created,duplicates},{status:201});}
