"use client";

import { useEffect,useMemo,useState } from "react";

type CalendarEvent={id:string;source:"FOLLOW_UP"|"AUDIO"|"VIDEO"|"VISIT";enqNo:string;companyName:string;clientName:string;title:string;startsAt:string;notes:string};
const dateKey=(value:string)=>String(value||"").slice(0,10);
const monthTitle=(date:Date)=>new Intl.DateTimeFormat("en-IN",{month:"long",year:"numeric"}).format(date);
const eventTime=(value:string)=>value.includes("T")?new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(value)):"All day";

export default function DashboardCalendar({onOpenLead}:{onOpenLead:(enqNo:string)=>void}){
  const [month,setMonth]=useState(()=>{const now=new Date();return new Date(now.getFullYear(),now.getMonth(),1);});
  const [events,setEvents]=useState<CalendarEvent[]>([]),[loading,setLoading]=useState(true),[selectedDate,setSelectedDate]=useState(""),[removingId,setRemovingId]=useState("");
  const load=()=>{setLoading(true);fetch("/api/calendar-events").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setEvents(data.events||[]);}).catch(()=>setEvents([])).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const cells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),offset=(first.getDay()+6)%7,count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return [...Array(offset).fill(null),...Array.from({length:count},(_,i)=>i+1)];},[month]);
  const eventsByDate=useMemo(()=>events.reduce<Record<string,CalendarEvent[]>>((map,event)=>{const key=dateKey(event.startsAt);(map[key]||=[]).push(event);return map;},{}),[events]);
  const selectedEvents=useMemo(()=>selectedDate?[...(eventsByDate[selectedDate]||[])].sort((a,b)=>String(a.startsAt).localeCompare(String(b.startsAt))):[],[eventsByDate,selectedDate]);
  const shift=(amount:number)=>setMonth(value=>new Date(value.getFullYear(),value.getMonth()+amount,1));
  const removeEvent=async(event:CalendarEvent)=>{if(removingId||!window.confirm(`Remove ${event.title} for ${event.companyName} from the calendar? The underlying CRM record will be retained.`))return;setRemovingId(event.id);try{const response=await fetch(`/api/calendar-events?id=${encodeURIComponent(event.id)}`,{method:"DELETE"}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Event could not be removed.");setEvents(items=>items.filter(item=>item.id!==event.id));}catch(error){window.alert(error instanceof Error?error.message:"Event could not be removed.");}finally{setRemovingId("");}};
  return <article className="panel dashboard-calendar">
    <div className="panel-head"><div><span className="eyebrow">TEAM ACTIVITY CALENDAR</span><h2>Calls, visits & next actions</h2><p>Completed Log Action entries are excluded; only scheduled next actions appear.</p></div><div className="calendar-controls"><button onClick={()=>shift(-1)} aria-label="Previous month">‹</button><b>{monthTitle(month)}</b><button onClick={()=>shift(1)} aria-label="Next month">›</button><button onClick={()=>{const now=new Date();setMonth(new Date(now.getFullYear(),now.getMonth(),1));setSelectedDate(dateKey(now.toISOString()));}}>Today</button><button onClick={load}>Refresh</button></div></div>
    {loading?<div className="calendar-loading">Loading scheduled CRM activity…</div>:<><div className="calendar-weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><b key={day}>{day}</b>)}</div><div className="calendar-grid">{cells.map((day,index)=>{if(!day)return <span className="calendar-blank" key={`blank-${index}`}/>;const key=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,dayEvents=eventsByDate[key]||[],today=dateKey(new Date().toISOString())===key;return <button className={`${dayEvents.length?"has-events":""} ${selectedDate===key?"selected":""} ${today?"today":""}`} onClick={()=>setSelectedDate(key)} key={key}><strong>{day}</strong><div>{dayEvents.slice(0,3).map(event=><span className={`calendar-event ${event.source.toLowerCase()}`} key={event.id}><i/>{event.companyName}<small>{event.title}</small></span>)}{dayEvents.length>3&&<em>+{dayEvents.length-3} more</em>}</div></button>;})}</div>
    {selectedDate&&<section className="calendar-agenda"><header><div><span className="eyebrow">DAILY AGENDA</span><h3>{new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${selectedDate}T00:00:00`))}</h3></div><button onClick={()=>setSelectedDate("")}>Close</button></header>{selectedEvents.map(event=><div className="calendar-agenda-row" key={event.id}><button onClick={()=>onOpenLead(event.enqNo)}><i className={event.source.toLowerCase()}/><span><b>{event.title} · {event.companyName}</b><small>{event.enqNo} · {event.clientName} · {eventTime(event.startsAt)}</small><em>{event.notes}</em></span><strong>Open lead →</strong></button><button className="calendar-remove-event" disabled={removingId===event.id} onClick={()=>removeEvent(event)}>{removingId===event.id?"Removing…":"Remove"}</button></div>)}{!selectedEvents.length&&<p>No calls, visits or follow-ups scheduled for this date.</p>}</section>}</>}
  </article>;
}
