"use client";

import { useEffect,useMemo,useState } from "react";

type Lead={enq:string;company:string;contact:string;bua?:number};
type Process={name:string;sequence:string;cycleTime:string;batchSize:string;changeoverTime:string;changeoversPerShift:string;inspection:string[];operators:string[];totalWorkers:string;machineNames:string[];machineName?:string;numberOfOperators:number};
type Product={family:string;name:string;bom:string;annualDemand:number;monthlyDemand:number;weight:string;salesMonths:string[];processes:Process[]};
type Machine={name:string;id:string;type:string;dimensions:string;utilities:string;oee:string;utilisation:string};
type Flow={from:string;to:string;distance:string;frequency:string;container:string;handlingMethod:string};
type Attachment={name:string;type:string;data:string};
type Payload={products:Product[];machines:Machine[];machineAttachment?:Attachment;materialFlows:Flow[];building:Record<string,string>;constraints:string[];deliverables:string[]};
type Row={id:number;enqNo:string;companyName:string;clientName:string;payload:Payload;updatedAt:string};

const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const inspectionOptions=["Inward","In Process","Outward"];
const operatorOptions=["Skilled","Semi skilled","Helpers","All types"];
const constraints=["Poor Material Flow","Excessive Handling","Long Travel Distance","Poor Space Utilisation","Bottleneck Operations","Inefficient Machine Placement","Congested Work Areas","Inadequate Storage Layout","Excessive WIP","Unsafe Material Movement","Poor Utility Distribution","Future Expansion Constraints"];
const deliverables=["2D CAD Gemba Layout","Factory Master Plan","Industrial Architectural Drawings","Structural Drawings","Utility Layouts","Warehouse Layout","Office Layout","Landscaping","Temple / Gurudwara / Church / Masjid","Visual Factory","VCS","BIM Model","3D Walkthrough","Construction Roadmap"];
const buildingFields=["Plot Area","Built-up Area","Production Area","Warehouse Area","Clear Height","Column Grid","Floor Load","Loading Bays"];
const emptyProcess=():Process=>({name:"",sequence:"",cycleTime:"",batchSize:"",changeoverTime:"",changeoversPerShift:"",inspection:[],operators:[],totalWorkers:"",machineNames:[""],numberOfOperators:0});
const emptyProduct=():Product=>({family:"",name:"",bom:"",annualDemand:0,monthlyDemand:0,weight:"",salesMonths:[],processes:[emptyProcess()]});
const emptyMachine=():Machine=>({name:"",id:"",type:"",dimensions:"",utilities:"",oee:"",utilisation:""});
const emptyFlow=():Flow=>({from:"",to:"",distance:"",frequency:"",container:"",handlingMethod:""});
const empty=():Payload=>({products:[emptyProduct()],machines:[emptyMachine()],materialFlows:[emptyFlow()],building:Object.fromEntries(buildingFields.map(item=>[item,""])),constraints:[],deliverables:[]});

function Checks({items,selected,toggle}:{items:string[];selected:string[];toggle:(item:string)=>void}){
  return <div className="check-grid factory-check-grid">{items.map(item=><label key={item}><input type="checkbox" checked={selected.includes(item)} onChange={()=>toggle(item)}/>{item}</label>)}</div>;
}

export default function FactoryDataPanel({leads,toast}:{leads:Lead[];toast:(message:string)=>void}){
  const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[editor,setEditor]=useState<Row|null>(null),[data,setData]=useState<Payload>(empty());
  const load=()=>{setLoading(true);Promise.all([fetch("/api/information-gathering?type=AUDIO"),fetch("/api/factory-data")]).then(async responses=>{if(responses.some(response=>!response.ok))throw new Error();const [audioData,factoryData]=await Promise.all(responses.map(response=>response.json()));const saved=new Map<string,Row>((factoryData.records||[]).map((row:Row)=>[row.enqNo,row]));const seen=new Set<string>(),eligible:Row[]=[];for(const audio of audioData.records||[]){if(seen.has(audio.enqNo))continue;seen.add(audio.enqNo);const lead=leads.find(item=>item.enq===audio.enqNo);eligible.push(saved.get(audio.enqNo)||{id:0,enqNo:audio.enqNo,companyName:audio.companyName||lead?.company||"",clientName:audio.clientName||lead?.contact||"",payload:empty(),updatedAt:""});}setRows(eligible);}).catch(()=>toast("Factory data could not be loaded.")).finally(()=>setLoading(false));};
  useEffect(load,[leads]);
  const filtered=useMemo(()=>rows.filter(row=>`${row.enqNo} ${row.companyName} ${row.clientName}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
  const machineRefs=data.products.flatMap((product,productIndex)=>product.processes.flatMap((process,processIndex)=>(process.machineNames?.length?process.machineNames:[""]).map((name,machineIndex)=>({name,productName:product.name||`Product ${productIndex+1}`,processName:`${process.name||`Process ${processIndex+1}`} · Machine ${machineIndex+1}`}))));
  const open=(row:Row)=>{
    const defaults=empty(),payload=row.payload||defaults;
    const legacy=payload as Payload&{processSequence?:string;cycleTime?:string;batchSize?:string;changeoverTime?:string;changeoversPerShift?:string;totalWorkers?:string;inspection?:string[];operators?:string[];machineName?:string;numberOfOperators?:number};
    const products=(payload.products?.length?payload.products:[emptyProduct()]).map((product,productIndex)=>{
      const sourceProcesses=product.processes?.length?product.processes:productIndex===0&&legacy.processSequence?[{...emptyProcess(),name:"Legacy manufacturing process",sequence:legacy.processSequence,cycleTime:legacy.cycleTime||"",batchSize:legacy.batchSize||"",changeoverTime:legacy.changeoverTime||"",changeoversPerShift:legacy.changeoversPerShift||"",totalWorkers:legacy.totalWorkers||""}]:[emptyProcess()];
      return {...emptyProduct(),...product,monthlyDemand:product.monthlyDemand??product.annualDemand/12,salesMonths:product.salesMonths||[],processes:sourceProcesses.map((process,processIndex)=>({...emptyProcess(),...process,inspection:process.inspection?.length?process.inspection:productIndex===0&&processIndex===0?legacy.inspection||[]:[],operators:process.operators?.length?process.operators:productIndex===0&&processIndex===0?legacy.operators||[]:[],machineNames:[process.machineNames?.[0]||process.machineName||(productIndex===0&&processIndex===0?legacy.machineName||"":"")],numberOfOperators:process.numberOfOperators??(productIndex===0&&processIndex===0?legacy.numberOfOperators||0:0)}))};
    });
    const machineReferences=products.flatMap((product,productIndex)=>product.processes.flatMap((process,processIndex)=>(process.machineNames?.length?process.machineNames:[""]).map((name,machineIndex)=>({name,productName:product.name||`Product ${productIndex+1}`,processName:`${process.name||`Process ${processIndex+1}`} · Machine ${machineIndex+1}`}))));
    const machines=[...machineReferences.map((reference,index)=>({...emptyMachine(),...(payload.machines?.[index]||{}),name:reference.name})),...(payload.machines||[]).slice(machineReferences.length).map(machine=>({...emptyMachine(),...machine}))];
    setEditor(row);setData({...defaults,...payload,products,machines,materialFlows:payload.materialFlows?.length?payload.materialFlows:[emptyFlow()],building:{...defaults.building,...(payload.building||{})},constraints:payload.constraints||[],deliverables:payload.deliverables||[]});
  };
  const updateProduct=(index:number,change:Partial<Product>)=>setData(value=>({...value,products:value.products.map((item,n)=>n===index?{...item,...change}:item)}));
  const updateProcess=(productIndex:number,processIndex:number,change:Partial<Process>)=>setData(value=>({...value,products:value.products.map((product,n)=>n===productIndex?{...product,processes:product.processes.map((process,p)=>p===processIndex?{...process,...change}:process)}:product)}));
  const toggleProcess=(productIndex:number,processIndex:number,key:"inspection"|"operators",item:string)=>{const selected=data.products[productIndex].processes[processIndex][key];updateProcess(productIndex,processIndex,{[key]:selected.includes(item)?selected.filter(value=>value!==item):[...selected,item]});};
  const toggle=(key:"constraints"|"deliverables",item:string)=>setData(value=>({...value,[key]:value[key].includes(item)?value[key].filter(entry=>entry!==item):[...value[key],item]}));
  const save=async()=>{if(!editor)return;const synchronizedMachines=machineRefs.map((reference,index)=>({...emptyMachine(),...(data.machines[index]||{}),name:reference.name})),additionalMachines=data.machines.slice(machineRefs.length),savedData={...data,machines:[...synchronizedMachines,...additionalMachines]};const response=await fetch("/api/factory-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({enqNo:editor.enqNo,payload:savedData})}),result=await response.json().catch(()=>({}));if(!response.ok){toast(result.error||"Factory data could not be saved.");return;}setEditor(null);load();toast("Factory engineering data saved in the database.");};
  const attach=async(file?:File)=>{if(!file)return;if(file.size>2_000_000){toast("Machine-list attachment must be smaller than 2 MB.");return;}const encoded=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});setData(value=>({...value,machineAttachment:{name:file.name,type:file.type,data:encoded}}));};

  return <div className="factory-data-page">
    <header className="leads-head"><div><span className="eyebrow">MASTER ENGINEERING DATABASE</span><h2>Factory Data Collection</h2><p>One consolidated engineering record for every Audio-qualified lead.</p></div></header>
    <section className="lead-search-panel"><div><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search company, enquiry or contact…"/>{query&&<button onClick={()=>setQuery("")}>Clear</button>}</div><p><b>{filtered.length}</b> records</p></section>
    <section className="panel"><div className="table-wrap"><table><thead><tr><th>LEAD / COMPANY</th><th>PRODUCTS</th><th>PROCESSES</th><th>MACHINES</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{filtered.map(row=><tr className="lead-clickable-row" key={row.enqNo} onClick={()=>open(row)}><td><b>{row.companyName}</b><small>{row.enqNo} · {row.clientName}</small></td><td>{row.id?row.payload.products?.length||0:"—"}</td><td>{row.id?row.payload.products?.reduce((total,product)=>total+(product.processes?.length||0),0):"—"}</td><td>{row.id?row.payload.machines?.length||0:"—"}</td><td><span className={`assessment-status ${row.id?"complete":"pending"}`}>{row.id?"Data captured":"Pending"}</span></td><td><button className="edit-lead-button" onClick={event=>{event.stopPropagation();open(row);}}>{row.id?"View / edit":"Start collection"}</button></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={6}>No leads have completed Audio Call qualification yet.</td></tr>}</tbody></table></div></section>
    {editor&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setEditor(null);}}><div className="drawer factory-data-drawer"><header><div><span className="eyebrow">FACTORY DATA · {editor.enqNo}</span><h2>{editor.companyName}</h2><p>Master engineering database</p></div><button className="close" onClick={()=>setEditor(null)}>×</button></header><div className="form-body factory-data-form">
      <h3>Products & Manufacturing Processes</h3>
      {data.products.map((product,productIndex)=><section className="factory-product-card" key={productIndex}>
        <header><div><span className="eyebrow">PRODUCT {String(productIndex+1).padStart(2,"0")}</span><h4>{product.name||"New product"}</h4></div><button className="delete-document" onClick={()=>setData(value=>({...value,products:value.products.filter((_,n)=>n!==productIndex)}))}>Remove product</button></header>
        <div className="factory-product-fields"><input placeholder="Product family" value={product.family} onChange={event=>updateProduct(productIndex,{family:event.target.value})}/><input placeholder="Product name" value={product.name} onChange={event=>updateProduct(productIndex,{name:event.target.value})}/><input placeholder="BOM part nos." value={product.bom} onChange={event=>updateProduct(productIndex,{bom:event.target.value})}/><input type="number" placeholder="Annual demand" value={product.annualDemand||""} onChange={event=>{const annual=Number(event.target.value);updateProduct(productIndex,{annualDemand:annual,monthlyDemand:annual/12});}}/><input readOnly value={product.monthlyDemand?`${product.monthlyDemand.toFixed(2)} / month`:"Monthly demand"}/><input placeholder="Weight" value={product.weight} onChange={event=>updateProduct(productIndex,{weight:event.target.value})}/><div className="month-selector"><b>Sales season (if any) — select months</b>{months.map(month=><label key={month}><input type="checkbox" checked={product.salesMonths.includes(month)} onChange={()=>updateProduct(productIndex,{salesMonths:product.salesMonths.includes(month)?product.salesMonths.filter(item=>item!==month):[...product.salesMonths,month]})}/>{month}</label>)}</div></div>
        <div className="product-processes"><div className="process-heading"><div><span className="eyebrow">MANUFACTURING</span><h4>Processes for {product.name||`Product ${productIndex+1}`}</h4></div><button className="add-row" onClick={()=>updateProduct(productIndex,{processes:[...product.processes,emptyProcess()]})}>＋ Add process</button></div>
          {product.processes.map((process,processIndex)=><article className="factory-process-card" key={processIndex}><header><b>Process {String(processIndex+1).padStart(2,"0")}</b><button className="delete-document" onClick={()=>updateProduct(productIndex,{processes:product.processes.filter((_,n)=>n!==processIndex)})}>Remove</button></header><div className="form-grid"><label>Process name<input value={process.name} onChange={event=>updateProcess(productIndex,processIndex,{name:event.target.value})}/></label><label>Total Cycle Time<input value={process.cycleTime} onChange={event=>updateProcess(productIndex,processIndex,{cycleTime:event.target.value})}/></label><label>Machine used in this process<input value={process.machineNames[0]||""} onChange={event=>updateProcess(productIndex,processIndex,{machineNames:[event.target.value]})}/></label><label>Batch Size<input value={process.batchSize} onChange={event=>updateProcess(productIndex,processIndex,{batchSize:event.target.value})}/></label><label>Changeover time<input value={process.changeoverTime} onChange={event=>updateProcess(productIndex,processIndex,{changeoverTime:event.target.value})}/></label><label>No. of changeovers / shift<input value={process.changeoversPerShift} onChange={event=>updateProcess(productIndex,processIndex,{changeoversPerShift:event.target.value})}/></label><label>Number of operators<input type="number" min="0" step="1" inputMode="numeric" value={process.numberOfOperators||""} onChange={event=>updateProcess(productIndex,processIndex,{numberOfOperators:Math.max(0,Math.trunc(Number(event.target.value)))})}/></label><label>Total number of workers/helpers<input value={process.totalWorkers} onChange={event=>updateProcess(productIndex,processIndex,{totalWorkers:event.target.value})}/></label><label className="wide">Process Sequence<textarea value={process.sequence} onChange={event=>updateProcess(productIndex,processIndex,{sequence:event.target.value})}/></label></div><b>Inspection</b><Checks items={inspectionOptions} selected={process.inspection} toggle={item=>toggleProcess(productIndex,processIndex,"inspection",item)}/><b>Operators</b><Checks items={operatorOptions} selected={process.operators} toggle={item=>toggleProcess(productIndex,processIndex,"operators",item)}/></article>)}
        </div>
      </section>)}
      <button className="add-row" onClick={()=>setData(value=>({...value,products:[...value.products,emptyProduct()]}))}>＋ Add product</button>

      <h3>Machines <small>({data.machines.length} total · {machineRefs.length} from product processes)</small></h3><div className="machine-section-actions"><label className="factory-attachment">Attach machine list<input type="file" accept=".xlsx,.xls,.csv,.pdf,.doc,.docx" onChange={event=>attach(event.target.files?.[0])}/>{data.machineAttachment&&<span>{data.machineAttachment.name}</span>}</label><button className="add-row" onClick={()=>setData(value=>({...value,machines:[...value.machines,emptyMachine()]}))}>＋ Add machine</button></div>{machineRefs.map((reference,index)=>{const machine=data.machines[index]||emptyMachine();return <div className="factory-repeat-row machine-synced-row" key={`${reference.productName}-${reference.processName}-${index}`}><input readOnly aria-label="Machine name" value={reference.name} placeholder="Machine name from product process"/><input readOnly aria-label="Product and process" value={`${reference.productName} · ${reference.processName}`}/>{(["id","type","dimensions","utilities","oee","utilisation"] as const).map(key=><input key={key} placeholder={key==="id"?"Machine ID":key[0].toUpperCase()+key.slice(1)} value={machine[key]} onChange={event=>setData(value=>({...value,machines:Array.from({length:Math.max(value.machines.length,machineRefs.length)},(_,n)=>n===index?{...emptyMachine(),...(value.machines[n]||{}),name:reference.name,[key]:event.target.value}:value.machines[n]||{...emptyMachine(),name:machineRefs[n]?.name||""})}))}/>)}</div>})}{data.machines.slice(machineRefs.length).map((machine,extraIndex)=>{const index=machineRefs.length+extraIndex;return <div className="factory-repeat-row machine-manual-row" key={`manual-${extraIndex}`}><input placeholder="Machine name" value={machine.name} onChange={event=>setData(value=>({...value,machines:value.machines.map((item,n)=>n===index?{...item,name:event.target.value}:item)}))}/><input readOnly value="Additional machine"/>{(["id","type","dimensions","utilities","oee","utilisation"] as const).map(key=><input key={key} placeholder={key==="id"?"Machine ID":key[0].toUpperCase()+key.slice(1)} value={machine[key]} onChange={event=>setData(value=>({...value,machines:value.machines.map((item,n)=>n===index?{...item,[key]:event.target.value}:item)}))}/>)}<button className="delete-document" onClick={()=>setData(value=>({...value,machines:value.machines.filter((_,n)=>n!==index)}))}>Remove</button></div>})}{!data.machines.length&&<p className="assessment-empty">Add a machine or enter one under a product process.</p>}
      <h3>Material Flow</h3>{data.materialFlows.map((flow,index)=><div className="factory-repeat-row" key={index}>{(["from","to","distance","frequency","container","handlingMethod"] as const).map(key=><input key={key} placeholder={key==="distance"?"Approx. distance":key==="handlingMethod"?"Handling method":key[0].toUpperCase()+key.slice(1)} value={flow[key]} onChange={event=>setData(value=>({...value,materialFlows:value.materialFlows.map((item,n)=>n===index?{...item,[key]:event.target.value}:item)}))}/>)}<button className="delete-document" onClick={()=>setData(value=>({...value,materialFlows:value.materialFlows.filter((_,n)=>n!==index)}))}>Remove</button></div>)}<button className="add-row" onClick={()=>setData(value=>({...value,materialFlows:[...value.materialFlows,emptyFlow()]}))}>＋ Add material flow</button>
      <h3>Building</h3><div className="form-grid">{buildingFields.map(item=><label key={item}>{item}<input value={data.building[item]||""} onChange={event=>setData(value=>({...value,building:{...value.building,[item]:event.target.value}}))}/></label>)}</div>
      <h3>Constraints</h3><Checks items={constraints} selected={data.constraints} toggle={item=>toggle("constraints",item)}/>
      <h3>Deliverables Required</h3><Checks items={deliverables} selected={data.deliverables} toggle={item=>toggle("deliverables",item)}/>
      <div className="drawer-actions"><button onClick={()=>setEditor(null)}>Cancel</button><button className="primary" onClick={save}>Save factory data</button></div>
    </div></div></div>}
  </div>;
}
