export const importedLeads = [
  {
    "enq": "E2627079",
    "company": "Ar. Hareesh (Ref. Mayur Gaikwad)",
    "contact": "Ar. Hareesh (Ref. Mayur Gaikwad)",
    "email": "",
    "phone": "9916721238",
    "city": "Banglore (Plant Khalapur)",
    "project": "To qualify",
    "bua": 0,
    "source": "Ref. Mayur Gaikwad",
    "status": "Lead Received",
    "lastAction": "21-07-2026- kaka is calling them at 12:30pm today",
    "nextAction": "Qualifying phone call",
    "age": "2026-07-21",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627078",
    "company": "Vhrushi India Pvt Ltd",
    "contact": "Rushikesh Mali",
    "email": "",
    "phone": "9146658624",
    "city": "Satara",
    "project": "Greenfield",
    "bua": 8555,
    "source": "Workbook",
    "status": "Engagement Initiated",
    "lastAction": "20-07-2026- Called",
    "nextAction": "Review visit outcome",
    "age": "2026-07-20",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627077",
    "company": "Precicast Company",
    "contact": "Vaibhav Minajagi",
    "email": "vibhav.minajagi@padmavatiauto.com",
    "phone": "9158434345",
    "city": "Kolhapur",
    "project": "Light Greenfield",
    "bua": 12000,
    "source": "Old Enq",
    "status": "Engagement Initiated",
    "lastAction": "18-07- vcall set on Monday 20-07-2026",
    "nextAction": "Plan site visit / proposal",
    "age": "2026-07-18",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627076",
    "company": "Bendy Products",
    "contact": "Gaurav Bhosale",
    "email": "",
    "phone": "9834649087",
    "city": "Vadodara, Gujrat",
    "project": "Light Greenfield",
    "bua": 152460,
    "source": "old enq in 2019 project done",
    "status": "Lead Received",
    "lastAction": "18- July - Called and mailed them requiremts require for 3D walkthrough videos",
    "nextAction": "Qualifying phone call",
    "age": "2026-07-18",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627075",
    "company": "MEK",
    "contact": "Ajay Singh",
    "email": "ajaykhutail46@gmail.com",
    "phone": "98107 31110",
    "city": "Ghaziabad",
    "project": "Greenfield",
    "bua": 600,
    "source": "old enq",
    "status": "Proposal Sent",
    "lastAction": "08-07-2026- Called mainsh their designer - 9540676883",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 403892.76,
    "proposalNo": "2627P019",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627074",
    "company": "Satish Dharap",
    "contact": "Satish Dharap",
    "email": "",
    "phone": "9930947541, 9869402304",
    "city": "Satara",
    "project": "Greenfield",
    "bua": 0,
    "source": "Kaka enq",
    "status": "Converted",
    "lastAction": "Visit done on 11-07-2026-",
    "nextAction": "Project delivery / next milestone",
    "age": "2026-07-05",
    "value": 106200,
    "proposalNo": "2627P022",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627073",
    "company": "UHD Enterprises",
    "contact": "Ismail Mulla",
    "email": "jiyauddinmulla79@gmail.com",
    "phone": "9922963624",
    "city": "Satara",
    "project": "Light Greenfield",
    "bua": 10000,
    "source": "SMM",
    "status": "Converted",
    "lastAction": "Their partner is in germany will come afer 3 months so will connect after 3 months",
    "nextAction": "Project delivery / next milestone",
    "age": "Imported",
    "value": 122400,
    "proposalNo": "2627P05",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627072",
    "company": "Khemraj Bakery",
    "contact": "Santosh Bandekar",
    "email": "khemraj_b@yahoo.co.in",
    "phone": "7385766671",
    "city": "Kolhapur",
    "project": "Light Greenfield",
    "bua": 13650,
    "source": "SMM",
    "status": "Converted",
    "lastAction": "CONVERTED",
    "nextAction": "Project delivery / next milestone",
    "age": "Imported",
    "value": 122750,
    "proposalNo": "2627P004",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627071",
    "company": "FMT Pvt Ltd.",
    "contact": "Ajay Kulkarni",
    "email": "",
    "phone": "8600700490",
    "city": "Supa",
    "project": "Greenfield",
    "bua": 0,
    "source": "WOM",
    "status": "Proposal Sent",
    "lastAction": "Project on Hold",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 1300000,
    "proposalNo": "2627006",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627070",
    "company": "Quantic Auto",
    "contact": "Dilip Patil",
    "email": "",
    "phone": "9922431966",
    "city": "Bhosari",
    "project": "Greenfield",
    "bua": 0,
    "source": "WOM",
    "status": "Proposal Sent",
    "lastAction": "Project on Hold",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 300000,
    "proposalNo": "2627002",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627069",
    "company": "Maruti products",
    "contact": "Prathamesh Lad",
    "email": "marutiproducts1@gmail.com",
    "phone": "9545219980",
    "city": "Kolhapur",
    "project": "To qualify",
    "bua": 0,
    "source": "WOM",
    "status": "Proposal Sent",
    "lastAction": "Project need to start",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 200000,
    "proposalNo": "NA",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627068",
    "company": "Madhuri offset Pvt Ltd",
    "contact": "Milind Patil",
    "email": "sales@madhurioffset.com",
    "phone": "8956563514",
    "city": "Nashik",
    "project": "Brownfield",
    "bua": 12000,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "Had Vcall with their daughter from Germany on 8-07-2026- Will share dimension willl move further",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627067",
    "company": "Shripant Industries",
    "contact": "Shelar Avadhut",
    "email": "",
    "phone": "9557977577",
    "city": "Islampur, MIDC kolhapur-",
    "project": "To qualify",
    "bua": 72,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "V call set on 4July- Visit Required",
    "nextAction": "Closed — not worthy",
    "age": "2026-07-03",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627066",
    "company": "Classique Elements",
    "contact": "Murtuza Balasinorwala",
    "email": "msbalasinorwala@gmail.com",
    "phone": "85251786263",
    "city": "Kheda Plant,Ahmedabad, Gujrat ,",
    "project": "Greenfield",
    "bua": 18000,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "Vcall done  04-07-2026, Visited Office 14-07-2026",
    "nextAction": "Review visit outcome",
    "age": "2026-07-03",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627065",
    "company": "Rohan cards and printing press",
    "contact": "Shriniwas Chandrakanth Pathak",
    "email": "",
    "phone": "8087872209",
    "city": "Viman nagar-- Pune",
    "project": "Greenfield",
    "bua": 15000,
    "source": "from kaka-enq came",
    "status": "Proposal Sent",
    "lastAction": "Visit done on 09-07-2026",
    "nextAction": "Proposal follow-up",
    "age": "2026-07-02",
    "value": 694784,
    "proposalNo": "2627P020",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627064",
    "company": "Swanandmilkproducts",
    "contact": "Vikrant Deshmukh",
    "email": "swananddairy@gmail.com",
    "phone": "919657770799",
    "city": "Ahmed Nagar",
    "project": "To qualify",
    "bua": 8000,
    "source": "Workbook",
    "status": "Lead Received",
    "lastAction": "call",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627063",
    "company": "Sunbeam cooling systems india pvt ltd",
    "contact": "Sujit Samant",
    "email": "sujit@sunbeamcooling.com",
    "phone": "9821014132",
    "city": "Kolhapur- Karad Highway",
    "project": "Brownfield",
    "bua": 50000,
    "source": "SMM",
    "status": "Proposal Sent",
    "lastAction": "Visit done on 11-07-2026\nvcall done on 2-07-2026, Visited our office on 12-07-2026",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 127050,
    "proposalNo": "2627P021",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627062",
    "company": "Chh India pvt ltd",
    "contact": "Prakash Patil",
    "email": "pspatil100@gmail.com",
    "phone": "7045911711",
    "city": "Thane, Bhiwandi",
    "project": "Brownfield",
    "bua": 10000,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "Not able to attend got up in traffic- called didnt respond",
    "nextAction": "Plan site visit / proposal",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627061",
    "company": "Mauli Laser Tech",
    "contact": "Vishal Dhumal",
    "email": "mauli.mkt@gmail.com",
    "phone": "919922468881",
    "city": "Pune",
    "project": "To qualify",
    "bua": 23500,
    "source": "Workbook",
    "status": "Lead Received",
    "lastAction": "Call again",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627060",
    "company": "Utsav foods",
    "contact": "Yogesh Agarwal",
    "email": "utsav.masala@yahoo.com",
    "phone": "9960229922",
    "city": "Pune",
    "project": "Greenfield",
    "bua": 25,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "Visit plan",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627059",
    "company": "Karan Enggineering works",
    "contact": "Uday",
    "email": "udaydhamale928@rediffmail.com",
    "phone": "919822216117",
    "city": "Pune",
    "project": "To qualify",
    "bua": 5000,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "small area- Drop",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627058",
    "company": "Kurade Food Industries",
    "contact": "Rahul Kurade",
    "email": "",
    "phone": "919922499797",
    "city": "Kolhapur",
    "project": "Brownfield",
    "bua": 40000,
    "source": "Workbook",
    "status": "Engagement Initiated",
    "lastAction": "30-06-2026-Called didnt reach drop msg-02-07-2026- didnt received- 03-07-2026- Didnt received",
    "nextAction": "Plan site visit / proposal",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627057",
    "company": "Kakade Laser",
    "contact": "Pratik kakade",
    "email": "",
    "phone": "8956728469",
    "city": "Pune",
    "project": "Greenfield",
    "bua": 50,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "7-July, Monday conf call set",
    "nextAction": "Closed — not worthy",
    "age": "2026-06-30",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627056",
    "company": "Anant hydro Engineers llp",
    "contact": "Prafulla Natu",
    "email": "pnn@anantengg.com",
    "phone": "919921050026",
    "city": "Ahilyanagar",
    "project": "To qualify",
    "bua": 4000,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "Call again",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627055",
    "company": "Girish tea company",
    "contact": "Girish chughra",
    "email": "girish_tea@yahoo.co.in",
    "phone": "919422292621",
    "city": "Jalgaon",
    "project": "To qualify",
    "bua": 10000,
    "source": "Workbook",
    "status": "Lead Received",
    "lastAction": "Call again",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627054",
    "company": "Shinde",
    "contact": "Atul Shinde",
    "email": "atulshinde20@gmail.com",
    "phone": "919975609976",
    "city": "Pune",
    "project": "To qualify",
    "bua": 8000,
    "source": "Workbook",
    "status": "Lead Received",
    "lastAction": "Call again",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627053",
    "company": "Swapnil Dhomane (Ashish shinkar ref )",
    "contact": "Swapnil Dhomane (Ashish shinkar ref )",
    "email": "",
    "phone": "9096350799",
    "city": "Sinnar, Nasik",
    "project": "To qualify",
    "bua": 0,
    "source": "Workbook",
    "status": "Lead Received",
    "lastAction": "call  again",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627052",
    "company": "Yom India Pvt Ltd",
    "contact": "Parmeshwar Thite (Enq received from kaka)",
    "email": "",
    "phone": "9797974799",
    "city": "Khedshivpur, Pune",
    "project": "Light Greenfield",
    "bua": 50000,
    "source": "SMM",
    "status": "Proposal Sent",
    "lastAction": "Visit date plan",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 0,
    "proposalNo": "Sheet metal fabrication - Acostic Encloser manufacturer",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627051",
    "company": "PlastLink Chain Belt",
    "contact": "Ankush Handge",
    "email": "plastlinkbelt@gmail.com",
    "phone": "9158286898",
    "city": "Dehu, Pune",
    "project": "Light Greenfield",
    "bua": 10000,
    "source": "Workbook",
    "status": "Proposal Sent",
    "lastAction": "Shared proposal -waiting for confirmation",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 91450,
    "proposalNo": "2627P018",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627050",
    "company": "Motawane Manufacturing",
    "contact": "Anant patil",
    "email": "patil.anant@motwane.com",
    "phone": "9271306182",
    "city": "Nasik, Satpur",
    "project": "Brownfield",
    "bua": 5000,
    "source": "Enquiry from linkdin",
    "status": "Engagement Initiated",
    "lastAction": "29-06-2026- Called didnt received- drop msg about dates available 4july- weekly off- plan visit date",
    "nextAction": "Review visit outcome",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627049",
    "company": "Nilakshi Bhoir",
    "contact": "Nilakshi Bhoir",
    "email": "nilexim2014@gmail.com",
    "phone": "8369462040",
    "city": "Thane",
    "project": "To qualify",
    "bua": 0,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627048",
    "company": "Ironweld Engineering Pvt Ltd",
    "contact": "Ravindra Mule",
    "email": "ravi.mule@ironweldengineering.com",
    "phone": "919881746042",
    "city": "Pune",
    "project": "To qualify",
    "bua": 50000,
    "source": "Workbook",
    "status": "Lead Received",
    "lastAction": "Told to kaka",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627047",
    "company": "Arihant Alucast Alloy pvt ltd",
    "contact": "Mahavir Arasgonda",
    "email": "arihantalucast09@gmail.com",
    "phone": "919850961509",
    "city": "Ichalkaranji",
    "project": "To qualify",
    "bua": 9000,
    "source": "Workbook",
    "status": "Lead Received",
    "lastAction": "Make 2 call",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627046",
    "company": "Matrix life science pvt ltd",
    "contact": "Kalim Jamdar",
    "email": "kalim@matrixlifescience.com",
    "phone": "917767812182",
    "city": "Aurangabad",
    "project": "Greenfield",
    "bua": 3,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "* planning new factory of 80mx40m G+2 or G+3 structure\n* almost a chemical plant\n* SET VISIT w/c 22 JUNE",
    "nextAction": "Closed — not worthy",
    "age": "2026-06-17",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627045",
    "company": "Matrix life science pvt ltd",
    "contact": "Kalim Inamdar",
    "email": "kalim@matrixlifescience.com",
    "phone": "7767812182",
    "city": "Aurangabad",
    "project": "Greenfield",
    "bua": 3,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "Visit Date confirmed- 15 july second half",
    "nextAction": "Closed — not worthy",
    "age": "2026-06-17",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627044",
    "company": "Siddhagiri enterprises",
    "contact": "Chinmay Sanjay shedge",
    "email": "esiddhagiri@yahoo.com",
    "phone": "7083337444",
    "city": "Pimpri Chinchwad Pune",
    "project": "To qualify",
    "bua": 10000,
    "source": "Workbook",
    "status": "Engagement Initiated",
    "lastAction": "DOUBTFUL- Will confirm with hus father- No response",
    "nextAction": "Plan site visit / proposal",
    "age": "2026-06-17",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627043",
    "company": "Rawtech Engineers",
    "contact": "Atul Nadkarni",
    "email": "atulnadkarni@gmail.com",
    "phone": "7620210990",
    "city": "Pune",
    "project": "To qualify",
    "bua": 6500,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "Small area leave it-Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "2026-06-17",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627042",
    "company": "Samarth engineering",
    "contact": "Kiran Pathare",
    "email": "kiran.5210@gmail.com",
    "phone": "9881007447",
    "city": "Pune",
    "project": "Brownfield",
    "bua": 12000,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627041",
    "company": "Samarth engineering",
    "contact": "Kiran Pathare",
    "email": "kiran.5210@gmail.com",
    "phone": "9881007447",
    "city": "Pune",
    "project": "Brownfield",
    "bua": 12000,
    "source": "Workbook",
    "status": "Engagement Initiated",
    "lastAction": "Call after 15 july- is out off",
    "nextAction": "Plan site visit / proposal",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627040",
    "company": "Pemraj Industries",
    "contact": "Pradeep Narayan Dhore",
    "email": "pemrajind@gmail.com",
    "phone": "919822007645",
    "city": "Pune",
    "project": "To qualify",
    "bua": 0,
    "source": "Workbook",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627039",
    "company": "Kawad Engineering Company",
    "contact": "Prakash kawad",
    "email": "pbkawad@gmail.com",
    "phone": "9881436321",
    "city": "Ahilyanagar",
    "project": "Greenfield",
    "bua": 5000,
    "source": "SMM",
    "status": "Proposal Sent",
    "lastAction": "Shared Proposal - Revised again",
    "nextAction": "Proposal follow-up",
    "age": "2026-06-15",
    "value": 206500,
    "proposalNo": "2627P016",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627038",
    "company": "SV METATECH INDIA PVT. LTD.",
    "contact": "Sandeep hatkar",
    "email": "sandeep@svmetatech.com",
    "phone": "9823746161",
    "city": "Koregaon, bhima, pune",
    "project": "Light Greenfield",
    "bua": 14300,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "Need to call-Arrange call",
    "nextAction": "Review future trigger",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627037",
    "company": "Parmar Techno Forge",
    "contact": "Bhushan Parmar",
    "email": "sales@parmarpipefittings.com",
    "phone": "919588472374",
    "city": "Pune",
    "project": "To qualify",
    "bua": 0,
    "source": "Workbook",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627036",
    "company": "SHREE SAI IND",
    "contact": "Raju",
    "email": "raju.bargukar@yahoo.com",
    "phone": "919623459977",
    "city": "Pune",
    "project": "Brownfield",
    "bua": 2000,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "Small area leave it-Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627035",
    "company": "GH techno world",
    "contact": "Amit Jogi",
    "email": "amitjogi20@gmail.com",
    "phone": "8793267812",
    "city": "Sambhaji Nagar",
    "project": "Brownfield",
    "bua": 6000,
    "source": "SMM",
    "status": "Proposal Sent",
    "lastAction": "Finding new area in MIDC will connect",
    "nextAction": "Proposal follow-up",
    "age": "2026-06-15",
    "value": 89800,
    "proposalNo": "2627P014",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627034",
    "company": "Manil engineers",
    "contact": "Vitthal",
    "email": "mtwopune@gmail.com",
    "phone": "918530090303",
    "city": "Pimpri-Chinchwad",
    "project": "Brownfield",
    "bua": 10000,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "26-06-2026- Didnt received shared details",
    "nextAction": "Review future trigger",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627033",
    "company": "KLASS MOLD",
    "contact": "Prasad Honarao",
    "email": "prasadklass@gmail.com",
    "phone": "9890295252",
    "city": "Bhosari,Pune",
    "project": "Brownfield",
    "bua": 5000,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "Small and brownfield leave it",
    "nextAction": "Plan site visit / proposal",
    "age": "2026-06-15",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627032",
    "company": "Jor Chakli",
    "contact": "Amirth Kumar",
    "email": "amirthkumar0002@gmail.com",
    "phone": "8883411000",
    "city": "Kolhapur",
    "project": "Greenfield",
    "bua": 4000,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "Due to budget said no- Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627031",
    "company": "Lotus Geo Lotus Global private Limited",
    "contact": "Raj Varma",
    "email": "raj.varma@kamalimpex.com",
    "phone": "9822094605",
    "city": "Nasik",
    "project": "Greenfield",
    "bua": 22000,
    "source": "Workbook",
    "status": "Proposal Sent",
    "lastAction": "Visit Date plan after 15july call",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 704960,
    "proposalNo": "2627P015",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627030",
    "company": "Frutzee",
    "contact": "Kishor Shinde",
    "email": "kishorshinde.frutzee@gmail.com",
    "phone": "919763772006",
    "city": "Wai",
    "project": "Brownfield",
    "bua": 6000,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627029",
    "company": "Bajaji graphic ind",
    "contact": "Sarfraj Gadwale",
    "email": "sgenterprises4646@gmail.com",
    "phone": "919823949459",
    "city": "Kolhapur",
    "project": "To qualify",
    "bua": 0,
    "source": "Workbook",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627028",
    "company": "Sarvadnya Electrotech Pvt Ltd",
    "contact": "Jayesh Patil",
    "email": "jayesh.patil@setpl.in",
    "phone": "918308000000",
    "city": "Pune",
    "project": "To qualify",
    "bua": 0,
    "source": "OptiSpace-Lead",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627027",
    "company": "Sunil Sankpal",
    "contact": "Sunil Sankpal",
    "email": "adinfra1@gmail.com",
    "phone": "9881877277",
    "city": "Pune",
    "project": "To qualify",
    "bua": 0,
    "source": "OptiSpace-Lead",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627026",
    "company": "Bapu",
    "contact": "Bapu",
    "email": "bapunarute@gmail.com",
    "phone": "917218920620",
    "city": "Founder",
    "project": "To qualify",
    "bua": 0,
    "source": "OptiSpace-Lead",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627025",
    "company": "Hunk jet laser",
    "contact": "Manoj parbhane",
    "email": "hunkjetl510@gmail.com",
    "phone": "91 88885-10510",
    "city": "Pune, hinjavdi",
    "project": "Brownfield",
    "bua": 5000,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "Small area-Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627024",
    "company": "Anjali T Precision",
    "contact": "Nitin Ghorpade",
    "email": "nitin@anjalitprecision.com",
    "phone": "91 98222-60377",
    "city": "Pune",
    "project": "To qualify",
    "bua": 45000,
    "source": "Workbook",
    "status": "On Hold",
    "lastAction": "No requirements yet HOLD",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627023",
    "company": "Kanal Enterprises",
    "contact": "Aditya Tanwani",
    "email": "aditya.tanwani@gmail.com",
    "phone": "919340745803",
    "city": "Ceo",
    "project": "Brownfield",
    "bua": 60000,
    "source": "OptiSpace-Lead",
    "status": "Lead Received",
    "lastAction": "Call again",
    "nextAction": "Qualifying phone call",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627022",
    "company": "True color print",
    "contact": "Nitin Kandar",
    "email": "kandarnitin@gmail.com",
    "phone": "9833 563820",
    "city": "Mumbai",
    "project": "To qualify",
    "bua": 0,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "Call again",
    "nextAction": "Plan site visit / proposal",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627021",
    "company": "Daso Clothings",
    "contact": "Sanjay Dadasaheb Jadhav",
    "email": "sanjaydj2@gmail.com",
    "phone": "976 3573057",
    "city": "Wagholi - Pune",
    "project": "Brownfield",
    "bua": 1500,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "Unresponsive",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627020",
    "company": "Vikram &Vikrams Foods",
    "contact": "Vikram Sonawane",
    "email": "vikram21sonawane@gmail.com",
    "phone": "94 22718845",
    "city": "Undri, Pune",
    "project": "Brownfield",
    "bua": 10000,
    "source": "Workbook",
    "status": "Engagement Initiated",
    "lastAction": "Told amount in vcall - No response",
    "nextAction": "Plan site visit / proposal",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627019",
    "company": "Indrajaya Agri",
    "contact": "Pavan",
    "email": "pavanware9163@gmail.com",
    "phone": "920000000000",
    "city": "Pune",
    "project": "To qualify",
    "bua": 10000,
    "source": "Workbook",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627018",
    "company": "Vision Enterprises",
    "contact": "Rahul Shivajirao",
    "email": "rahul_thakare18@rediffmail.com",
    "phone": "98 607100 01",
    "city": "Pune",
    "project": "Green field",
    "bua": 10000,
    "source": "Workbook",
    "status": "STOP",
    "lastAction": "11-06-2026 vcall did-Just came to talk-Ignored by SO",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627017",
    "company": "Phoenix enterprises",
    "contact": "Apurv",
    "email": "apurvpatwardhan77@gmail.com",
    "phone": "7 774 969-20-2",
    "city": "Talwade, Pune",
    "project": "Brownfield",
    "bua": 10000,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "vcall set on 27-06-2026 at 11:30am- Not available no response",
    "nextAction": "Plan site visit / proposal",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Pitch V Call"
  },
  {
    "enq": "E2627016",
    "company": "Infinity windoors",
    "contact": "Ashish Shinkar",
    "email": "ashish.shinkar@gmail.com",
    "phone": "93 70760573",
    "city": "Nashik",
    "project": "Brownfield",
    "bua": 15000,
    "source": "SMM",
    "status": "Converted",
    "lastAction": "29-06-2026- July 3rd date confirmed for visit",
    "nextAction": "Project delivery / next milestone",
    "age": "Imported",
    "value": 97500,
    "proposalNo": "2627P011",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627015",
    "company": "Acumen Industries",
    "contact": "Aashwin J Girolla",
    "email": "aashwing123@gmail.com",
    "phone": "9850193880",
    "city": "Nashik",
    "project": "Brownfield",
    "bua": 1500,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "ignoring area is too small",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627014",
    "company": "Shri Krishna Kanhaiya Dairy Farms Private Limited",
    "contact": "Ubale pratap",
    "email": "pu2197@gmail.com",
    "phone": "98228-47526",
    "city": "Pune",
    "project": "Greenfield",
    "bua": 43560,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "Available for  visit after 7 July",
    "nextAction": "Review visit outcome",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627013",
    "company": "R A Masala",
    "contact": "Ravindra Divate",
    "email": "ravidivate11111@gmail.com",
    "phone": "7 (588) 055-55-5",
    "city": "Tasgaon, Sangli",
    "project": "Greenfield",
    "bua": 87120,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "Not Responding- Taken multiiple followups",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627012",
    "company": "Unique Engineers",
    "contact": "Sudhir Rajmane",
    "email": "unique.engineers2006@gmail.com",
    "phone": "98 810 878 57",
    "city": "Kolhapur",
    "project": "Brownfield",
    "bua": 2500,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "Unresponsive",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627011",
    "company": "Laxmi Sagar Engineers Pvt Ltd",
    "contact": "Laxmikant",
    "email": "laxmikant@laxmisagar.in",
    "phone": "98 812 567 02",
    "city": "Pune",
    "project": "Greenfield",
    "bua": 20000,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "(Old enq )Site visit plan",
    "nextAction": "Review visit outcome",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627010",
    "company": "Phoenix Industries",
    "contact": "Harshal wagh",
    "email": "harshalwaghnsk@gmail.com",
    "phone": "7350514340",
    "city": "Nashik",
    "project": "Light Greenfield",
    "bua": 24000,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "29-06-2026- Called didnt received- drop msg about dates available 4july",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627009",
    "company": "Ghatge enterprises",
    "contact": "Prithviraj ghatge",
    "email": "prithvighatge@gmail.com",
    "phone": "91 94220-00231",
    "city": "Pune",
    "project": "Brownfield",
    "bua": 4000,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "Ignore by SO",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627008",
    "company": "New Union Enterprises",
    "contact": "Yogesh Dongarsane",
    "email": "newunionent@yahoo.co.in",
    "phone": "91 77199-27711",
    "city": "Kolhapur",
    "project": "Brownfield",
    "bua": 5000,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "Didnt req service",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627007",
    "company": "Evershine Air System",
    "contact": "Jiyauddin Mujawar",
    "email": "jiyamujawar@gmail.com",
    "phone": "9325288686",
    "city": "Karad",
    "project": "Brownfield",
    "bua": 6000,
    "source": "SMM",
    "status": "STOP",
    "lastAction": "Ignored SO",
    "nextAction": "Closed — not worthy",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627006",
    "company": "N B Enterprises",
    "contact": "Bharat",
    "email": "bagal.bharat@gmail.com",
    "phone": "91 7798012355",
    "city": "Pune",
    "project": "To qualify",
    "bua": 7500,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "Unresponsive",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627005",
    "company": "Oxynext Biotech Pvt Ltd",
    "contact": "Sachin Nivrutti Auti",
    "email": "oxygroup1@gmail.com",
    "phone": "9930671367",
    "city": "Pune",
    "project": "Brownfield",
    "bua": 8000,
    "source": "SMM",
    "status": "Proposal Sent",
    "lastAction": "Project is too small to negotiate",
    "nextAction": "Proposal follow-up",
    "age": "Imported",
    "value": 66080,
    "proposalNo": "2627009",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627004",
    "company": "acg Pharma technology",
    "contact": "Sharad Dhaigude",
    "email": "sharadr.dhaigude@gmail.com",
    "phone": "9067764829",
    "city": "Satara",
    "project": "To qualify",
    "bua": 80000,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "When requied will contact HOLD",
    "nextAction": "Review future trigger",
    "age": "Imported",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  },
  {
    "enq": "E2627003",
    "company": "Pradip Plastic Moulders Pvt Ltd",
    "contact": "Aditya Lakhani",
    "email": "aditya.lakhani@pradipplastic.com",
    "phone": "9370147255",
    "city": "Pune",
    "project": "Brownfield",
    "bua": 80000,
    "source": "SMM",
    "status": "Proposal Sent",
    "lastAction": "Not responding to proposal- multiple feedbacks taken",
    "nextAction": "Proposal follow-up",
    "age": "2026-06-08",
    "value": 141600,
    "proposalNo": "2627008",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627002",
    "company": "S G Equipments",
    "contact": "Rupesh Mishra",
    "email": "sgequipments1@gmail.com",
    "phone": "9823133397",
    "city": "Nashik",
    "project": "Greenfield",
    "bua": 10010,
    "source": "SMM",
    "status": "Engagement Initiated",
    "lastAction": "29-06-2026- will see proposal then revert construction going on when asked then come",
    "nextAction": "Plan site visit / proposal",
    "age": "2026-06-05",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 2"
  },
  {
    "enq": "E2627001",
    "company": "Pawan subhashrao",
    "contact": "Pawan subhashrao",
    "email": "pawanshisode7@gmail.com",
    "phone": "9421504444",
    "city": "Paithan",
    "project": "To qualify",
    "bua": 0,
    "source": "SMM",
    "status": "On Hold",
    "lastAction": "No information disclosed-Didnt required service right now-HOLD",
    "nextAction": "Review future trigger",
    "age": "2026-06-04",
    "value": 0,
    "proposalNo": "",
    "sourceSheet": "Phase 1"
  }
] as const;
export const importMetadata = {
  "source": "Leads Management 2026-27.xlsx",
  "importedOn": "21 July 2026",
  "total": 79,
  "counts": {
    "Lead Received": 10,
    "Engagement Initiated": 15,
    "Proposal Sent": 13,
    "Converted": 4,
    "On Hold": 17,
    "STOP": 20
  }
} as const;
