"use client";

import { useEffect, useMemo, useState } from "react";

type Lead={enq:string;company:string;contact:string;phone:string;city:string};
type CallType="AUDIO"|"VIDEO";
type Payload={participants:string;duration:number;discussion:string;requirements:string;outcome:string;nextAction:string;nextFollowUp:string};
type RecordRow={id:number;enqNo:string;callType:CallType;payload:Payload;occurredAt:string;createdAt:string;updatedAt:string;companyName:string;clientName:string};
const emptyPayload:Payload={participants:"",duration:0,discussion:"",requirements:"",outcome:"Follow-up required",nextAction:"",nextFollowUp:""};
const nowLocal=()=>{const date=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return date.toISOString().slice(0,16);};
const formatDate=(value:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));

function Pagination({total,page,size,setPage,setSize}:{total:number;page:number;size:number;setPage:(value:number)=>void;setSize:(value:number)=>void}){
  const pages=Math.max(1,Math.ceil(total/size)),current=Math.min(page,pages);
  return <div className="pagination-controls"><label>Rows per page<select value={size} onChange={event=>setSize(Number(event.target.value))}>{[10,25,50,100].map(value=><option key={value}>{value}</option>)}</select></label><span>Page {current} of {pages}</span><button disabled={current<=1} onClick={()=>setPage(current-1)}>‹</button><button className="current">{current}</button><button disabled={current>=pages} onClick={()=>setPage(current+1)}>›</button></div>;
}

export default function InformationGatheringPanel({leads,toast}:{leads:Lead[];toast:(message:string)=>void}){
  const [activeType,setActiveType]=useState<CallType>("AUDIO"),[rows,setRows]=useState<RecordRow[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[page,setPage]=useState(1),[size,setSize]=useState(10);
  const [editor,setEditor]=useState<RecordRow|null|undefined>(undefined),[enqNo,setEnqNo]=useState(""),[leadSearch,setLeadSearch]=useState(""),[occurredAt,setOccurredAt]=useState(nowLocal()),[payload,setPayload]=useState<Payload>({...emptyPayload});
  const load=async()=>{setLoading(true);try{const response=await fetch(`/api/information-gathering?type=${activeType}`),data=await response.json();setRows(data.records||[]);}finally{setLoading(false);}};
  useEffect(()=>{load();setPage(1);},[activeType]);
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();if(!needle)return rows;return rows.filter(row=>[row.enqNo,row.companyName,row.clientName,row.payload.participants,row.payload.discussion,row.payload.requirements,row.payload.outcome,row.payload.nextAction].some(value=>String(value||"").toLowerCase().includes(needle)));},[rows,query]);
  const pages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,pages),shown=filtered.slice((safePage-1)*size,safePage*size);
  useEffect(()=>setPage(1),[query,size]);
  const selectLead=(value:string)=>{setLeadSearch(value);const lead=leads.find(item=>`${item.company} — ${item.enq}`===value||item.enq.toLowerCase()===value.toLowerCase()||item.company.toLowerCase()===value.toLowerCase());setEnqNo(lead?.enq||"");setPayload(current=>({...current,participants:lead?.contact||current.participants}));};
  const create=()=>{setEditor(null);setEnqNo("");setLeadSearch("");setOccurredAt(nowLocal());setPayload({...emptyPayload});};
  const open=(row:RecordRow)=>{setEditor(row);setEnqNo(row.enqNo);setLeadSearch(`${row.companyName} — ${row.enqNo}`);setOccurredAt(row.occurredAt.slice(0,16));setPayload({...emptyPayload,...row.payload});};
  const close=()=>setEditor(undefined);
  const update=(key:keyof Payload,value:string|number)=>setPayload(current=>({...current,[key]:value}));
  const save=async()=>{if(!enqNo){toast("Please select a valid lead.");return;}if(!payload.discussion.trim()){toast("Discussion summary is required.");return;}const response=await fetch("/api/information-gathering",{method:editor?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:editor?.id,enqNo,callType:activeType,occurredAt:new Date(occurredAt).toISOString(),payload})}),data=await response.json().catch(()=>({error:"Information could not be saved."}));if(!response.ok){toast(data.error||"Information could not be saved.");return;}await load();close();toast(`${activeType==="AUDIO"?"Audio":"Video"} call information saved.`);};
  const remove=async(row:RecordRow)=>{if(!window.confirm(`Delete this ${row.callType==="AUDIO"?"audio":"video"} call record for ${row.companyName}?`))return;const response=await fetch(`/api/information-gathering?id=${row.id}`,{method:"DELETE"});if(!response.ok){toast("Record could not be deleted.");return;}if(editor?.id===row.id)close();await load();toast("Information record deleted.");};
  return <div className="information-page">
    <header className="leads-head information-head"><div><span className="eyebrow">CLIENT DISCOVERY DATABASE</span><h2>Information Gathering</h2><p>Capture structured requirements and decisions from client conversations.</p></div><button className="primary" onClick={create}>＋ Add {activeType==="AUDIO"?"audio":"video"} call</button></header>
    <div className="information-tabs" role="tablist" aria-label="Information gathering type"><button role="tab" aria-selected={activeType==="AUDIO"} className={activeType==="AUDIO"?"selected":""} onClick={()=>{setActiveType("AUDIO");close();}}>☎ <span>Audio Call</span><b>{activeType==="AUDIO"?rows.length:""}</b></button><button role="tab" aria-selected={activeType==="VIDEO"} className={activeType==="VIDEO"?"selected":""} onClick={()=>{setActiveType("VIDEO");close();}}>▣ <span>Video Call</span><b>{activeType==="VIDEO"?rows.length:""}</b></button></div>
    <section className="lead-search-panel"><div><span>⌕</span><input placeholder={`Search all ${activeType==="AUDIO"?"audio":"video"} call records…`} value={query} onChange={event=>setQuery(event.target.value)}/>{query&&<button onClick={()=>setQuery("")}>Clear</button>}</div><p><b>{filtered.length}</b> matching records</p></section>
    <section className="panel information-register"><div className="table-wrap"><table><thead><tr><th>LEAD / COMPANY</th><th>CALL DATE</th><th>PARTICIPANTS</th><th>DURATION</th><th>DISCUSSION</th><th>OUTCOME</th><th>NEXT ACTION</th><th>ACTION</th></tr></thead><tbody>{shown.map(row=><tr className="lead-clickable-row" key={row.id} onClick={()=>open(row)}><td><b>{row.companyName}</b><small>{row.enqNo} · {row.clientName}</small></td><td>{formatDate(row.occurredAt)}</td><td>{row.payload.participants||"—"}</td><td>{row.payload.duration?`${row.payload.duration} min`:"—"}</td><td className="information-summary">{row.payload.discussion}</td><td><span className="information-outcome">{row.payload.outcome}</span></td><td>{row.payload.nextAction||"—"}<small>{row.payload.nextFollowUp||""}</small></td><td><div className="document-row-actions"><button className="edit-lead-button" onClick={event=>{event.stopPropagation();open(row);}}>View / edit</button><button className="delete-document" onClick={event=>{event.stopPropagation();remove(row);}}>Delete</button></div></td></tr>)}{!loading&&!shown.length&&<tr><td colSpan={8}>No {activeType==="AUDIO"?"audio":"video"} call information has been recorded.</td></tr>}</tbody></table></div><footer className="table-foot"><span>Showing {shown.length} of {filtered.length} records</span><Pagination total={filtered.length} page={safePage} size={size} setPage={setPage} setSize={setSize}/></footer></section>
    {editor!==undefined&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)close();}}><section className="drawer information-drawer"><header><div><span className="eyebrow">{editor?"EDIT":"NEW"} {activeType==="AUDIO"?"AUDIO CALL":"VIDEO CALL"}</span><h2>Information gathering</h2><p>Link the conversation to a lead and capture actionable details.</p></div><button className="close" onClick={close}>×</button></header><div className="form-body"><div className="form-grid"><label className="wide">Company / lead<input list="information-leads" value={leadSearch} onChange={event=>selectLead(event.target.value)} placeholder="Type company or enquiry…" autoComplete="off"/><datalist id="information-leads">{leads.map(lead=><option value={`${lead.company} — ${lead.enq}`} key={lead.enq}/>)}</datalist>{!enqNo&&<small className="client-selection-warning">Select a valid company / lead.</small>}</label><label>Call date and time<input type="datetime-local" value={occurredAt} onChange={event=>setOccurredAt(event.target.value)}/></label><label>Duration (minutes)<input type="number" min="0" value={payload.duration||""} onChange={event=>update("duration",Number(event.target.value))}/></label><label className="wide">Participants<input value={payload.participants} onChange={event=>update("participants",event.target.value)} placeholder="Client and Solutions participants"/></label><label className="wide">Discussion summary<textarea value={payload.discussion} onChange={event=>update("discussion",event.target.value)} placeholder="What was discussed?" /></label><label className="wide">Requirements identified<textarea value={payload.requirements} onChange={event=>update("requirements",event.target.value)} placeholder="Area, machines, process, bottlenecks, expectations…" /></label><label>Outcome<select value={payload.outcome} onChange={event=>update("outcome",event.target.value)}><option>Follow-up required</option><option>Visit required</option><option>Proposal required</option><option>Decision pending</option><option>Not interested</option><option>Completed</option></select></label><label>Next follow-up<input type="date" value={payload.nextFollowUp} onChange={event=>update("nextFollowUp",event.target.value)}/></label><label className="wide">Next action<input value={payload.nextAction} onChange={event=>update("nextAction",event.target.value)} placeholder="Specific owner and next step"/></label></div><div className="drawer-actions">{editor&&<button className="delete-document" onClick={()=>remove(editor)}>Delete record</button>}<button onClick={close}>Cancel</button><button className="primary" onClick={save}>Save information</button></div></div></section></div>}
  </div>;
}
