"use client";

import { unzipSync, strFromU8 } from "fflate";
import { useState } from "react";

export type ImportLead={companyName:string;clientName:string;email:string;phone:string;city:string;plotArea:number;builtUpArea:number;areaUnit:string;operationNature:string;projectClass:string;enquirySource:string;products:string};
type ImportResult={created:number;duplicates:number;invalid:number;invalidRows:Array<{index:number;reason:string}>};

const normalise=(value:unknown)=>String(value??"").toLowerCase().replace(/[₹(),._/\\-]/g," ").replace(/\s+/g," ").trim();
const numberValue=(value:unknown)=>{const text=String(value??"").replace(/,/g,"");const match=text.match(/-?\d+(?:\.\d+)?/);return match?Number(match[0]):0;};
const phoneValue=(value:unknown)=>{const text=String(value??"").trim();if(!text)return "";if(/e[+-]?\d+$/i.test(text)){const numeric=Number(text);return Number.isFinite(numeric)?String(Math.trunc(numeric)):text;}if(/^\+?\d+\.0+$/.test(text))return text.replace(/\.0+$/g,"");return text;};
const first=(row:string[],headers:string[],patterns:RegExp[])=>{const index=headers.findIndex(header=>patterns.some(pattern=>pattern.test(header)));return index<0?"":String(row[index]??"").trim();};
const parseCsv=(text:string)=>{const rows:string[][]=[];let row:string[]=[],cell="",quote=false;for(let index=0;index<text.length;index++){const char=text[index];if(char==='"'&&text[index+1]==='"'){cell+='"';index++;continue;}if(char==='"'){quote=!quote;continue;}if(!quote&&(char===","||char==="\t")){row.push(cell);cell="";continue;}if(!quote&&(char==="\n"||char==="\r")){if(char==="\r"&&text[index+1]==="\n")index++;row.push(cell);if(row.some(value=>value.trim()))rows.push(row);row=[];cell="";continue;}cell+=char;}if(cell||row.length){row.push(cell);if(row.some(value=>value.trim()))rows.push(row);}return rows;};
const cellColumn=(ref:string)=>{const letters=ref.replace(/\d/g,"");return letters.split("").reduce((total,char)=>total*26+char.charCodeAt(0)-64,0)-1;};
function parseXlsx(buffer:ArrayBuffer,targetSheets?:RegExp[]){
  const files=unzipSync(new Uint8Array(buffer));
  const shared:string[]=[];
  if(files["xl/sharedStrings.xml"]){const document=new DOMParser().parseFromString(strFromU8(files["xl/sharedStrings.xml"]),"application/xml");document.querySelectorAll("si").forEach(item=>shared.push(Array.from(item.querySelectorAll("t")).map(node=>node.textContent||"").join("")));}
  const output:string[][]=[];
  let worksheetNames:string[]|undefined;
  if(targetSheets?.length && files["xl/workbook.xml"] && files["xl/_rels/workbook.xml.rels"]){
    const workbook=new DOMParser().parseFromString(strFromU8(files["xl/workbook.xml"]),"application/xml");
    const rels=new DOMParser().parseFromString(strFromU8(files["xl/_rels/workbook.xml.rels"]),"application/xml");
    const targets=new Set<string>();
    workbook.querySelectorAll("sheet").forEach(sheet=>{const sheetName=String(sheet.getAttribute("name")||"").trim();if(!targetSheets.some(pattern=>pattern.test(sheetName)))return;const relation=sheet.getAttribute("r:id")||sheet.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id")||"";const link=Array.from(rels.querySelectorAll("Relationship")).find(item=>item.getAttribute("Id")===relation)?.getAttribute("Target")||"";if(link)targets.add(`xl/${link.replace(/^\//,"")}`);});
    if(targets.size)worksheetNames=[...targets];
  }
  Object.keys(files).filter(name=>/^xl\/worksheets\/sheet\d+\.xml$/.test(name)).filter(name=>!worksheetNames||worksheetNames.includes(name)).sort().forEach(name=>{const document=new DOMParser().parseFromString(strFromU8(files[name]),"application/xml");document.querySelectorAll("sheetData > row").forEach(rowNode=>{const cells:string[]=[];rowNode.querySelectorAll(":scope > c").forEach(cell=>{const column=cellColumn(cell.getAttribute("r")||"");while(cells.length<=column)cells.push("");const type=cell.getAttribute("t");const value=cell.querySelector("v")?.textContent||cell.querySelector("t")?.textContent||"";cells[column]=type==="s"?shared[Number(value)]||"":value;});if(cells.some(value=>value.trim()))output.push(cells);});});
  return output;
}
function rowsToLeads(rows:string[][]){
  if(!rows.length)return [];
  let headerIndex=0,best=-1;
  rows.slice(0,30).forEach((row,index)=>{const headers=row.map(normalise);const score=headers.filter(value=>/company|email|phone|mobile|contact|name|built|plot|city|project|source|product|nature|operation/.test(value)).length;if(score>best){best=score;headerIndex=index;}});
  const headers=rows[headerIndex].map(normalise);
  return rows.slice(headerIndex+1).map(row=>{const plotArea=numberValue(first(row,headers,[/plot area/,/^area/,/square feet/,/sqft/]));return {companyName:first(row,headers,[/company/,/organisation/,/organization/,/^account$/]),clientName:first(row,headers,[/full name/,/^first name$/,/^name$/,/contact person/,/^contact$/]),email:first(row,headers,[/email/,/e mail/]),phone:phoneValue(first(row,headers,[/phone/,/mobile/,/contact number/])),city:first(row,headers,[/^city/,/location/,/address/]),plotArea,builtUpArea:numberValue(first(row,headers,[/built up/,/built-up/,/building area/,/^bua/]))||plotArea,areaUnit:/sqm|sq m|square meter/i.test(row.join(" "))?"SqM":"SqFt",operationNature:first(row,headers,[/nature/,/operation/,/product manufactured/,/manufacturing/]),projectClass:first(row,headers,[/project type/,/project class/,/building type/])||"Greenfield",enquirySource:first(row,headers,[/enq through/,/enquiry source/,/source/,/wom/,/smm/])||"Website",products:first(row,headers,[/^product$/, /products/,/service required/,/nature of operation/])};}).filter(row=>row.companyName||row.clientName||row.email||row.phone);
}
export async function parseLeadFile(file:File,options?:{sourceSheets?:RegExp[]}){const lower=file.name.toLowerCase();if(lower.endsWith(".csv")||lower.endsWith(".tsv"))return rowsToLeads(parseCsv(await file.text()));if(lower.endsWith(".xlsx"))return rowsToLeads(parseXlsx(await file.arrayBuffer(),options?.sourceSheets));throw new Error("Please upload an .xlsx, .csv or .tsv file.");}

export default function LeadImportPanel({toast}:{toast:(message:string)=>void}){
  const [fileName,setFileName]=useState(""),[rows,setRows]=useState<ImportLead[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[result,setResult]=useState<ImportResult|null>(null);
  const choose=async(file?:File)=>{if(!file)return;setFileName(file.name);setResult(null);setMessage("Reading workbook…");try{const parsed=await parseLeadFile(file);setRows(parsed);setMessage(`${parsed.length} lead rows detected. Review the preview, then import.`);}catch(error){setRows([]);setMessage(error instanceof Error?error.message:"The file could not be read.");}};
  const importRows=async()=>{if(!rows.length)return;setBusy(true);setResult(null);try{const response=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({leads:rows})});const data=await response.json().catch(()=>({}));if(!response.ok&&!data.created){throw new Error(data.error||"Import failed.");}const summary={created:Number(data.created||0),duplicates:Number(data.duplicates||0),invalid:Number(data.invalid||0),invalidRows:data.invalidRows||[]};setResult(summary);setMessage(`${summary.created} new lead${summary.created===1?"":"s"} added. Existing duplicates were skipped.`);toast(`${summary.created} new leads imported; ${summary.duplicates} duplicates skipped.`);}catch(error){setMessage(error instanceof Error?error.message:"Import failed. Please retry.");}finally{setBusy(false);}};
  return <div className="lead-import-page"><header className="leads-head"><div><span className="eyebrow">LEAD DATABASE</span><h2>Import new leads</h2><p>Upload the Excel lead register and add only new companies to the CRM.</p></div></header><section className="panel lead-import-card"><div className="lead-import-upload"><label className="lead-import-drop"><span className="lead-import-icon">⇧</span><b>Choose Excel or CSV file</b><small>Supports .xlsx, .csv and .tsv</small><input type="file" accept=".xlsx,.csv,.tsv" onChange={event=>choose(event.target.files?.[0])}/></label><div className="lead-import-help"><h3>Duplicate protection</h3><p>Rows are compared with existing leads by email, phone number, or company + contact name. Duplicate rows are skipped and never create another enquiry.</p><p>Required for a new record: company, contact, phone and built-up area.</p></div></div>{fileName&&<div className="lead-import-file"><b>{fileName}</b><span>{rows.length} rows ready</span></div>}{message&&<p className="lead-import-message">{message}</p>}{rows.length>0&&<><div className="panel-head lead-import-preview-head"><div><span className="eyebrow">PREVIEW</span><h3>Rows to import</h3></div><button className="primary" disabled={busy} onClick={importRows}>{busy?"Importing…":"Import new leads"}</button></div><div className="table-wrap lead-import-preview"><table><thead><tr><th>COMPANY</th><th>CONTACT</th><th>EMAIL</th><th>PHONE</th><th>CITY</th><th>BUILT-UP AREA</th><th>PROJECT</th></tr></thead><tbody>{rows.slice(0,8).map((row,index)=><tr key={`${row.companyName}-${index}`}><td>{row.companyName||"—"}</td><td>{row.clientName||"—"}</td><td>{row.email||"—"}</td><td>{row.phone||"—"}</td><td>{row.city||"—"}</td><td>{row.builtUpArea||"—"} {row.areaUnit}</td><td>{row.projectClass}</td></tr>)}</tbody></table></div>{rows.length>8&&<small className="lead-import-more">Showing first 8 rows of {rows.length}.</small>}</>}{result&&<div className="lead-import-result"><article><strong>{result.created}</strong><span>New leads created</span></article><article><strong>{result.duplicates}</strong><span>Duplicates skipped</span></article><article><strong>{result.invalid}</strong><span>Invalid rows</span></article></div>}</section></div>;
}
