"use client";

import { useEffect, useMemo, useState } from "react";
import { ImportLead, parseLeadFile } from "./lead-import-panel";

type RawLead=ImportLead & {id:number;sourceFile:string;sourceSheet:string;sourceRow:number;claimedEnqNo:string;createdAt:string};

export default function RawLeadsPanel({toast}:{toast:(message:string)=>void}){
  const [rows,setRows]=useState<RawLead[]>([]),[query,setQuery]=useState(""),[fileName,setFileName]=useState(""),[preview,setPreview]=useState<ImportLead[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState<{created:number;duplicates:number}|null>(null);
  const load=()=>fetch("/api/raw-leads").then(response=>response.ok?response.json():Promise.reject()).then(data=>setRows(data.rawLeads||[])).catch(()=>toast("Raw lead data could not be loaded."));
  useEffect(load,[]);
  const choose=async(file?:File)=>{if(!file)return;setFileName(file.name);setResult(null);setMessage("Reading workbook…");try{const parsed=await parseLeadFile(file,{sourceSheets:[/pune area leads july august/i,/^phase 1$/i]});setPreview(parsed);setMessage(`${parsed.length} rows detected from the requested source sheet(s). Upload them to the raw database.`);}catch(error){setPreview([]);setMessage(error instanceof Error?error.message:"The workbook could not be read.");}};
  const upload=async()=>{if(!preview.length)return;setBusy(true);try{const response=await fetch("/api/raw-leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceFile:fileName,rows:preview})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Raw data could not be saved.");setResult({created:Number(data.created||0),duplicates:Number(data.duplicates||0)});setMessage(`${data.created||0} new raw records saved; ${data.duplicates||0} duplicate raw records skipped.`);setPreview([]);await load();toast(`${data.created||0} raw lead records saved to the database.`);}catch(error){setMessage(error instanceof Error?error.message:"Raw data could not be saved.");}finally{setBusy(false);}};
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return rows.filter(row=>!needle||`${row.companyName} ${row.clientName} ${row.email} ${row.phone} ${row.city} ${row.sourceFile}`.toLowerCase().includes(needle));},[rows,query]);
  return <div className="raw-leads-page"><header className="leads-head"><div><span className="eyebrow">SOURCE DATABASE</span><h2>Raw lead data</h2><p>Store source workbook records before converting them into CRM leads.</p></div></header><section className="panel raw-upload-card"><div className="raw-upload-controls"><label className="lead-import-drop"><span className="lead-import-icon">⇧</span><b>Upload source workbook</b><small>Supports .xlsx, .csv and .tsv</small><input type="file" accept=".xlsx,.csv,.tsv" onChange={event=>choose(event.target.files?.[0])}/></label><div className="raw-upload-copy"><h3>Requested source sheets</h3><p><b>Pune Area Leads July August!</b> and <b>Phase 1</b> are stored as raw records. Nothing here creates a CRM lead until you select it in the lead form.</p>{fileName&&<span>{fileName} · {preview.length} rows ready</span>}{message&&<small>{message}</small>}<button className="primary" disabled={!preview.length||busy} onClick={upload}>{busy?"Saving…":"Save raw data"}</button></div></div>{result&&<div className="raw-result"><b>{result.created}</b><span>new raw records</span><b>{result.duplicates}</b><span>duplicates skipped</span></div>}</section><section className="panel raw-register"><div className="panel-head"><div><span className="eyebrow">RAW RECORDS</span><h2>{rows.length} source records</h2></div><label className="raw-search"><span>⌕</span><input placeholder="Search raw company, contact, phone or source…" value={query} onChange={event=>setQuery(event.target.value)}/></label></div><div className="table-wrap"><table><thead><tr><th>COMPANY</th><th>CONTACT</th><th>EMAIL</th><th>PHONE</th><th>CITY</th><th>SOURCE</th><th>LEAD STATUS</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><b>{row.companyName||"—"}</b><small>{row.products||"No product detail"}</small></td><td>{row.clientName||"—"}</td><td>{row.email||"—"}</td><td>{row.phone||"—"}</td><td>{row.city||"—"}</td><td><small>{row.sourceFile}</small>{row.sourceRow&&<small>Row {row.sourceRow}</small>}</td><td>{row.claimedEnqNo?<span className="raw-claimed">Created · {row.claimedEnqNo}</span>:<span className="raw-pending">Available for lead creation</span>}</td></tr>)}{!filtered.length&&<tr><td colSpan={7}>No raw lead records found. Upload a source workbook to begin.</td></tr>}</tbody></table></div></section></div>;
}
