"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type LeadOption={enq:string;company:string;contact:string;phone?:string;email?:string;city?:string;project?:string;bua?:number;products?:string;status?:string;engagementType?:string};
type Stakeholder={name:string;designation:string;mobile:string};
type StoredAttachment={name:string;type:string;data:string};
type Payload={
  designation:string;mobile:string;email:string;plantLocation:string;visitDate:string;visitTime:string;marketingEngineer:string;projectType:string;turnover:string;
  intent:string;industry:string;products:string;productionCapacity:string;builtUpArea:string;plotArea:string;completionTarget:string;
  existingStatus:string[];buildingPreferences:string[];floors:string;crane:string;tonnage:string;clearHeight:string;
  runnerProducts:string;stepFlow:string;machines:string;majorEquipment:string;specialProcesses:string;futureExpansion:string;expectedIncrease:string;
  utilities:Record<string,string>;services:string[];budget:string;decisionStages:string[];stakeholders:Stakeholder[];
  competitors:string[];competitorNames:string;priorities:string[];nextMeetingDate:string;clientRequirements:string[];otherRequirement:string;remarks:string;
  plotLayoutCad:string;factoryLayoutCad:string;processFlowObservation:string;materialFlowObservation:string;warehouseObservation:string;utilityRoomsObservation:string;
  expansionPossibility:string;safetyObservations:string;leanRatings:Record<string,number>;architecture:Record<string,string>;
  checklistAttachments:Record<string,StoredAttachment>;proposalExecutiveSummary:string;proposalProjectUnderstanding:string;proposalProjectObjectives:string;
};
type RecordRow={id:number;enqNo:string;companyName:string;clientName:string;payload:Payload;completedAt?:string;createdAt:string};

const existingOptions=["Land purchased","Land finalized","Land under discussion","Existing factory","Existing layout available","Building drawing available"];
const buildingOptions=["PEB","RCC","Combination","Not yet decided"];
const utilityOptions=["Power load","Air compressor","Water","ETP / STP","DG set","Fire fighting","Other utilities"];
const serviceOptions=["Gemba Study","Lean Factory Design","Machine Layout","Architectural Design","Structural Design","MEP Design","PEB Building","RCC Construction","Architectural Supervision","Project Management","Interior Design","Factory Approval Assistance","Complete Turnkey Solution"];
const decisionOptions=["Planning","Budgeting","Budget approval","Immediate start"];
const competitorOptions=["Architect","PEB Supplier","Contractor","PMC","Consultant"];
const priorityOptions=["Lowest cost","Fast completion","Best quality","Lean factory","Future expansion","Compliance"];
const requirementOptions=["Plot drawing","Google location","Process flow","Machine list","Product list","Existing layout","Utility requirement","Soil report","Other"];
const leanAssessmentOptions=["Material Flow","Machine Utilisation","Space Utilisation","WIP","Visual Management","Line Balancing","Storage","Safety","Housekeeping","Future Flexibility"];
const architectureOptions=["Building condition","Structural observations","Clear height","Column grid","Floor loading","Roads","Loading bays","Utilities","Fire exits","Office areas","Future expansion"];

const emptyPayload=():Payload=>({
  designation:"",mobile:"",email:"",plantLocation:"",visitDate:"",visitTime:"10:30",marketingEngineer:"",projectType:"",turnover:"",
  intent:"Expansion",industry:"",products:"",productionCapacity:"",builtUpArea:"",plotArea:"",completionTarget:"",
  existingStatus:[],buildingPreferences:[],floors:"",crane:"No",tonnage:"",clearHeight:"",
  runnerProducts:"",stepFlow:"",machines:"",majorEquipment:"",specialProcesses:"",futureExpansion:"No",expectedIncrease:"",
  utilities:Object.fromEntries(utilityOptions.map(item=>[item,""])),services:[],budget:"",decisionStages:[],stakeholders:[{name:"",designation:"",mobile:""}],
  competitors:[],competitorNames:"",priorities:[],nextMeetingDate:"",clientRequirements:[],otherRequirement:"",remarks:"",
  plotLayoutCad:"Not confirmed",factoryLayoutCad:"Not confirmed",processFlowObservation:"",materialFlowObservation:"",warehouseObservation:"",utilityRoomsObservation:"",
  expansionPossibility:"",safetyObservations:"",leanRatings:Object.fromEntries(leanAssessmentOptions.map(item=>[item,0])),architecture:Object.fromEntries(architectureOptions.map(item=>[item,""])),
  checklistAttachments:{},proposalExecutiveSummary:"",proposalProjectUnderstanding:"",proposalProjectObjectives:"",
});
const dateLabel=(value:string)=>new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(value));

function Pager({total,page,size,setPage,setSize}:{total:number;page:number;size:number;setPage:(n:number)=>void;setSize:(n:number)=>void}){
  const pages=Math.max(1,Math.ceil(total/size));return <div className="pagination-controls"><label>Rows per page<select value={size} onChange={e=>setSize(Number(e.target.value))}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><span>Page {page} of {pages}</span><button disabled={page<=1} onClick={()=>setPage(page-1)}>‹</button><button className="current">{page}</button><button disabled={page>=pages} onClick={()=>setPage(page+1)}>›</button></div>;
}

function SectionTitle({number,title,note}:{number:string;title:string;note:string}){return <div className="section-title"><span>{number}</span><div><b>{title}</b><small>{note}</small></div></div>;}
function Checks({items,selected,toggle}:{items:string[];selected:string[];toggle:(item:string)=>void}){return <div className="check-grid visit-check-grid">{items.map(item=><label key={item}><input type="checkbox" checked={selected.includes(item)} onChange={()=>toggle(item)}/> {item}</label>)}</div>;}

export default function VisitFormsPanel({leads,toast,initialEnq}:{leads:LeadOption[];toast:(message:string)=>void;initialEnq?:string}){
  const [rows,setRows]=useState<RecordRow[]>([]),[qualifiedLeads,setQualifiedLeads]=useState<LeadOption[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[size,setSize]=useState(10),[page,setPage]=useState(1);
  const [editor,setEditor]=useState<RecordRow|null|undefined>(undefined),[enqNo,setEnqNo]=useState(""),[clientSearch,setClientSearch]=useState(""),[clientWarning,setClientWarning]=useState(""),[data,setData]=useState<Payload>(emptyPayload());
  const [formTab,setFormTab]=useState<"DETAILS"|"CHECKLIST">("DETAILS");
  const load=()=>{setLoading(true);Promise.all([fetch("/api/visit-forms"),fetch("/api/information-gathering?type=AUDIO")]).then(async([visitResponse,audioResponse])=>{if(!visitResponse.ok||!audioResponse.ok)throw new Error();const [visitData,audioData]=await Promise.all([visitResponse.json(),audioResponse.json()]);const latestVisits=new Map<string,RecordRow>();for(const row of (visitData.visitForms||[]) as RecordRow[]){if(!latestVisits.has(row.enqNo))latestVisits.set(row.enqNo,row);}const eligibleEnquiries=[...new Set<string>([...(audioData.records||[]).map((row:{enqNo:string})=>row.enqNo),...latestVisits.keys(),...leads.filter(lead=>lead.engagementType==="ACTUAL_VISIT").map(lead=>lead.enq)])];const eligible=eligibleEnquiries.map(enq=>leads.find(lead=>lead.enq===enq)).filter(Boolean) as LeadOption[];setQualifiedLeads(eligible);setRows(eligible.map(lead=>latestVisits.get(lead.enq)||{id:0,enqNo:lead.enq,companyName:lead.company,clientName:lead.contact,payload:emptyPayload(),createdAt:""}));}).catch(()=>toast("Visit records could not be loaded.")).finally(()=>setLoading(false));};
  useEffect(()=>load(),[leads]);
  const filtered=useMemo(()=>rows.filter(r=>`${r.enqNo} ${r.companyName} ${r.clientName} ${r.payload.intent} ${r.payload.products} ${r.payload.industry||""}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
  const pages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,pages),shown=filtered.slice((safePage-1)*size,safePage*size);
  useEffect(()=>setPage(1),[query,size]);
  const field=<K extends keyof Payload>(key:K,value:Payload[K])=>setData(v=>({...v,[key]:value}));
  const toggle=(key:"existingStatus"|"buildingPreferences"|"services"|"decisionStages"|"competitors"|"priorities"|"clientRequirements",value:string)=>field(key,data[key].includes(value)?data[key].filter(x=>x!==value):[...data[key],value]);
  const clientLabel=(lead:LeadOption)=>`${lead.company} — ${lead.enq}`;
  const applyLead=(lead?:LeadOption)=>{setEnqNo(lead?.enq||"");if(!lead)return;setData(value=>({...value,mobile:lead.phone||value.mobile,email:lead.email||value.email,plantLocation:lead.city||value.plantLocation,projectType:lead.project||value.projectType,builtUpArea:lead.bua?String(lead.bua):value.builtUpArea,products:lead.products||value.products,stakeholders:value.stakeholders.length&&value.stakeholders[0].name?value.stakeholders:[{name:lead.contact||"",designation:"",mobile:lead.phone||""}]}));setClientWarning("");};
  const edit=(row:RecordRow)=>{const defaults=emptyPayload(),payload=row.payload||({} as Payload);setEditor(row.id?row:null);setFormTab("CHECKLIST");setEnqNo(row.enqNo);const lead=qualifiedLeads.find(item=>item.enq===row.enqNo);setClientSearch(lead?clientLabel(lead):`${row.companyName} — ${row.enqNo}`);setClientWarning("");setData({...defaults,...payload,mobile:payload.mobile||lead?.phone||"",email:payload.email||lead?.email||"",plantLocation:payload.plantLocation||lead?.city||"",projectType:payload.projectType||lead?.project||"",builtUpArea:payload.builtUpArea||(lead?.bua?String(lead.bua):""),products:payload.products||lead?.products||"",utilities:{...defaults.utilities,...(payload.utilities||{})},leanRatings:{...defaults.leanRatings,...(payload.leanRatings||{})},architecture:{...defaults.architecture,...(payload.architecture||{})},checklistAttachments:payload.checklistAttachments||{},existingStatus:payload.existingStatus||((payload as any).landChecks||[]),buildingPreferences:payload.buildingPreferences||((payload as any).structure?[String((payload as any).structure)]:[]),machines:String(payload.machines??""),floors:String(payload.floors??""),stakeholders:payload.stakeholders?.some(item=>item.name||item.designation||item.mobile)?payload.stakeholders:[{name:lead?.contact||row.clientName||"",designation:"",mobile:lead?.phone||""}]});};
  useEffect(()=>{if(initialEnq&&rows.length){const row=rows.find(item=>item.enqNo===initialEnq);if(row)edit(row);}},[initialEnq,rows]);
  const attach=async(key:string,file?:File)=>{if(!file)return;if(file.size>2_000_000){toast("Attachment must be smaller than 2 MB.");return;}const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});field("checklistAttachments",{...data.checklistAttachments,[key]:{name:file.name,type:file.type,data:dataUrl}});};
  const save=async(e:FormEvent)=>{e.preventDefault();if(!enqNo){setClientWarning("Please search and select a client before saving the visit form.");return;}setClientWarning("");const response=await fetch("/api/visit-forms",{method:editor?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:editor?.id,enqNo,payload:data,completed:true})});const result=await response.json().catch(()=>({}));if(!response.ok){toast(result.error||"Visit form could not be saved.");return;}setEditor(undefined);load();toast(editor?"Visit record updated in the database.":"Visit record saved in the database.");};
  const remove=async()=>{if(!editor||!window.confirm(`Delete visit record VF-${String(editor.id).padStart(4,"0")}? This will permanently remove it from the database.`))return;const response=await fetch(`/api/visit-forms?id=${editor.id}`,{method:"DELETE"});if(!response.ok){toast("Visit record could not be deleted.");return;}setEditor(undefined);load();toast("Visit record deleted from the database.");};

  return <div className="visit-records-page"><header className="leads-head"><div><span className="eyebrow">FIRST-VISIT DATABASE</span><h2>Visit forms</h2><p>Only leads with completed Audio Call qualification are available for Visit Form assessment.</p></div></header><section className="lead-search-panel"><div><span>⌕</span><input placeholder="Search company, enquiry, contact, intent, industry or products…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery("")}>Clear</button>}</div><p><b>{filtered.length}</b> matching records</p></section><section className="panel"><div className="table-wrap"><table><thead><tr><th>RECORD</th><th>LEAD / COMPANY</th><th>PROJECT INTENT</th><th>BUILDING</th><th>MACHINES</th><th>COMPLETED</th></tr></thead><tbody>{shown.map(row=><tr className="lead-clickable-row" key={row.enqNo} onClick={()=>edit(row)}><td><b>{row.id?`VF-${String(row.id).padStart(4,"0")}`:"Start visit form"}</b><small>{row.id?`Database record #${row.id}`:"Audio qualified"}</small></td><td><b>{row.companyName}</b><small>{row.enqNo} · {row.clientName}</small></td><td>{row.id?row.payload.intent:"Assessment pending"}<small>{row.payload.completionTarget||"No target date"}</small></td><td>{row.payload.buildingPreferences?.join(" · ")||(row.payload as any).structure||"Not selected"}<small>{row.payload.floors||"—"} floor(s)</small></td><td>{row.payload.machines||0}</td><td>{row.completedAt?dateLabel(row.completedAt):row.id?"Draft":"Pending"}</td></tr>)}{!loading&&!shown.length&&<tr><td colSpan={6}>No leads have completed Audio Call qualification yet.</td></tr>}</tbody></table></div><footer className="table-foot"><span>Showing {shown.length} of {filtered.length} qualified leads</span><Pager total={filtered.length} page={safePage} size={size} setPage={setPage} setSize={setSize}/></footer></section>
  {editor!==undefined&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setEditor(undefined);}}><div className="drawer visit-record-drawer"><header><div><span className="eyebrow">SOLUTIONS OPTISPACE · FORM NO. 2</span><h2>{editor?`Edit visit VF-${String(editor.id).padStart(4,"0")}`:"Create Visit Details Form"}</h2><p>Visit 01 · Database-backed industrial discovery</p></div><button className="close" onClick={()=>setEditor(undefined)}>×</button></header><form className={`form-body visit-form detailed-visit-form ${formTab==="CHECKLIST"?"checklist-mode":"details-mode"}`} onSubmit={save}>
    <div className="visit-form-subtabs"><button type="button" className={formTab==="DETAILS"?"selected":""} onClick={()=>setFormTab("DETAILS")}><span>▤</span> Visit Details</button><button type="button" className={formTab==="CHECKLIST"?"selected":""} onClick={()=>setFormTab("CHECKLIST")}><span>✓</span> Factory Visit Checklist</button></div>
    <SectionTitle number="01" title="Client information" note="Office and visit identification"/>
    <div className="form-grid"><label className="wide client-search-field">Client *<input list="visit-client-options" value={clientSearch} onChange={e=>{const value=e.target.value;setClientSearch(value);const match=qualifiedLeads.find(lead=>clientLabel(lead)===value||lead.enq.toLowerCase()===value.toLowerCase()||lead.company.toLowerCase()===value.toLowerCase());applyLead(match);}} placeholder="Search company or enquiry number…" autoComplete="off"/><datalist id="visit-client-options">{qualifiedLeads.map(lead=><option value={clientLabel(lead)} key={lead.enq}/>)}</datalist>{clientWarning&&<span className="client-selection-warning">⚠ {clientWarning}</span>}</label><label>Designation<input value={data.designation} onChange={e=>field("designation",e.target.value)}/></label><label>Mobile<input value={data.mobile} onChange={e=>field("mobile",e.target.value)}/></label><label>Email<input type="email" value={data.email} onChange={e=>field("email",e.target.value)}/></label><label>Plant location<input value={data.plantLocation} onChange={e=>field("plantLocation",e.target.value)}/></label><label>Date of visit<input type="date" value={data.visitDate} onChange={e=>field("visitDate",e.target.value)}/></label><label>Visit time<input type="time" value={data.visitTime} onChange={e=>field("visitTime",e.target.value)}/></label><label>Marketing engineer<input value={data.marketingEngineer} onChange={e=>field("marketingEngineer",e.target.value)}/></label><label>Project type<input value={data.projectType} onChange={e=>field("projectType",e.target.value)} placeholder="Green Field / Light Green Field…"/></label><label className="wide">Company turnover<input value={data.turnover} onChange={e=>field("turnover",e.target.value)} placeholder="₹ per year"/></label></div>

    <SectionTitle number="02" title="Project requirement" note="Facility scope, production and delivery target"/>
    <div className="form-grid"><label>New factory / expansion / relocation<select value={data.intent} onChange={e=>field("intent",e.target.value)}><option>New factory</option><option>Expansion</option><option>Relocation</option></select></label><label>Industry<input value={data.industry} onChange={e=>field("industry",e.target.value)}/></label><label className="wide">Products manufactured<textarea value={data.products} onChange={e=>field("products",e.target.value)}/></label><label>Expected production capacity<input value={data.productionCapacity} onChange={e=>field("productionCapacity",e.target.value)} placeholder="Units / month or expected increase"/></label><label>Proposed built-up area<input value={data.builtUpArea} onChange={e=>field("builtUpArea",e.target.value)} placeholder="SqFt"/></label><label>Plot area<input value={data.plotArea} onChange={e=>field("plotArea",e.target.value)} placeholder="SqFt / Acre"/></label><label>Expected completion time<input type="date" value={data.completionTarget} onChange={e=>field("completionTarget",e.target.value)}/></label></div>

    <SectionTitle number="03" title="Existing status" note="Land, factory and drawing readiness"/><Checks items={existingOptions} selected={data.existingStatus} toggle={item=>toggle("existingStatus",item)}/>

    <SectionTitle number="04" title="Building preference" note="Structure, floors, crane and clear height"/><Checks items={buildingOptions} selected={data.buildingPreferences} toggle={item=>toggle("buildingPreferences",item)}/><div className="form-grid"><label>Number of floors<input value={data.floors} onChange={e=>field("floors",e.target.value)}/></label><label>Crane required?<select value={data.crane} onChange={e=>field("crane",e.target.value)}><option>No</option><option>Yes</option></select></label><label>Maximum crane capacity<input value={data.tonnage} onChange={e=>field("tonnage",e.target.value)} placeholder="Ton"/></label><label>Building height required<input value={data.clearHeight} onChange={e=>field("clearHeight",e.target.value)} placeholder="ft"/></label></div>

    <SectionTitle number="05" title="Process understanding" note="Products, process, machinery and expansion"/><div className="form-grid"><label>Products (runners)<input value={data.runnerProducts} onChange={e=>field("runnerProducts",e.target.value)}/></label><label>Main manufacturing process<input value={data.stepFlow} onChange={e=>field("stepFlow",e.target.value)}/></label><label>Number of major machines<input value={data.machines} onChange={e=>field("machines",e.target.value)}/></label><label>Major equipment / utilities<input value={data.majorEquipment} onChange={e=>field("majorEquipment",e.target.value)}/></label><label className="wide">Special processes<textarea value={data.specialProcesses} onChange={e=>field("specialProcesses",e.target.value)}/></label><label>Future expansion planned?<select value={data.futureExpansion} onChange={e=>field("futureExpansion",e.target.value)}><option>No</option><option>Yes</option><option>Under discussion</option></select></label><label>Expected increase (%)<input value={data.expectedIncrease} onChange={e=>field("expectedIncrease",e.target.value)}/></label></div>

    <SectionTitle number="06" title="Utility requirement" note="Record requirement or capacity for every utility"/><div className="utility-grid">{utilityOptions.map(item=><label key={item}>{item}<input value={data.utilities[item]||""} onChange={e=>field("utilities",{...data.utilities,[item]:e.target.value})} placeholder="Requirement / capacity / status"/></label>)}</div>

    <SectionTitle number="07" title="Scope required" note="Select every service discussed"/><Checks items={serviceOptions} selected={data.services} toggle={item=>toggle("services",item)}/>

    <SectionTitle number="08" title="Investment expectation" note="Budget and decision stage"/><div className="form-grid"><label className="wide">Approximate project budget<input value={data.budget} onChange={e=>field("budget",e.target.value)} placeholder="₹"/></label></div><Checks items={decisionOptions} selected={data.decisionStages} toggle={item=>toggle("decisionStages",item)}/>

    <SectionTitle number="09" title="Decision makers" note="Names, designations and mobile numbers"/>{data.stakeholders.map((stakeholder,index)=><div className="stakeholder" key={index}><input aria-label="Decision maker name" placeholder="Name" value={stakeholder.name} onChange={e=>field("stakeholders",data.stakeholders.map((item,n)=>n===index?{...item,name:e.target.value}:item))}/><input aria-label="Decision maker designation" placeholder="Designation" value={stakeholder.designation} onChange={e=>field("stakeholders",data.stakeholders.map((item,n)=>n===index?{...item,designation:e.target.value}:item))}/><input aria-label="Decision maker mobile" placeholder="Mobile no." value={stakeholder.mobile} onChange={e=>field("stakeholders",data.stakeholders.map((item,n)=>n===index?{...item,mobile:e.target.value}:item))}/></div>)}<button type="button" className="add-row" onClick={()=>field("stakeholders",[...data.stakeholders,{name:"",designation:"",mobile:""}])}>＋ Add decision maker</button>

    <SectionTitle number="10" title="Competition" note="Other consultants and suppliers already contacted"/><Checks items={competitorOptions} selected={data.competitors} toggle={item=>toggle("competitors",item)}/><div className="form-grid"><label className="wide">Names, if known<textarea value={data.competitorNames} onChange={e=>field("competitorNames",e.target.value)}/></label></div>

    <SectionTitle number="11" title="Visit outcome" note="Client priorities and buying criteria"/><Checks items={priorityOptions} selected={data.priorities} toggle={item=>toggle("priorities",item)}/>

    <SectionTitle number="12" title="Action plan" note="Next meeting, inputs required and engineer remarks"/><div className="form-grid"><label>Next meeting date<input type="date" value={data.nextMeetingDate} onChange={e=>field("nextMeetingDate",e.target.value)}/></label></div><Checks items={requirementOptions} selected={data.clientRequirements} toggle={item=>toggle("clientRequirements",item)}/><div className="form-grid"><label className="wide">Other requirement<input value={data.otherRequirement} onChange={e=>field("otherRequirement",e.target.value)}/></label><label className="wide">Marketing engineer remarks<textarea className="visit-remarks" value={data.remarks} onChange={e=>field("remarks",e.target.value)} placeholder="Observations, commitments, risks and recommended next action"/></label></div>

    <div className="factory-checklist">
      <SectionTitle number="A" title="Existing Factory" note="Collect engineering observations and supporting evidence"/>
      <div className="form-grid"><label>Plot layout available in CAD?<select value={data.plotLayoutCad} onChange={e=>field("plotLayoutCad",e.target.value)}><option>Not confirmed</option><option>Yes</option><option>No</option></select></label><label>Existing factory layout available in CAD?<select value={data.factoryLayoutCad} onChange={e=>field("factoryLayoutCad",e.target.value)}><option>Not confirmed</option><option>Yes</option><option>No</option></select></label>{[["processFlowObservation","Process flow","processFlow"],["materialFlowObservation","Material flow observed","materialFlow"],["warehouseObservation","Warehouse inspected","warehouse"],["utilityRoomsObservation","Utility rooms inspected","utilityRooms"]].map(([key,label,attachmentKey])=><label className="wide checklist-write-attach" key={key}>{label}<textarea value={String(data[key as keyof Payload]||"")} onChange={e=>field(key as keyof Payload,e.target.value as never)} placeholder="Write observation…"/><span className="attachment-control"><input type="file" accept=".pdf,.png,.jpg,.jpeg,.dwg,.dxf,.doc,.docx,.xls,.xlsx" onChange={e=>attach(attachmentKey,e.target.files?.[0])}/>{data.checklistAttachments[attachmentKey]&&<em>Attached: {data.checklistAttachments[attachmentKey].name}</em>}</span></label>)}<label className="wide">Expansion possibility<textarea value={data.expansionPossibility} onChange={e=>field("expansionPossibility",e.target.value)}/></label><label className="wide">Safety observations<textarea value={data.safetyObservations} onChange={e=>field("safetyObservations",e.target.value)}/></label></div>

      <SectionTitle number="B" title="Lean Assessment" note="Rate each observation from 1 (poor) to 5 (excellent)"/>
      <div className="lean-rating-grid">{leanAssessmentOptions.map(item=><label key={item}><span>{item}</span><select value={data.leanRatings[item]||0} onChange={e=>field("leanRatings",{...data.leanRatings,[item]:Number(e.target.value)})}><option value="0">Not rated</option>{[1,2,3,4,5].map(value=><option value={value} key={value}>{value}</option>)}</select></label>)}</div>

      <SectionTitle number="C" title="Industrial Architecture" note="Building, structural, logistics and expansion observations"/>
      <div className="form-grid">{architectureOptions.map(item=><label className={item==="Structural observations"||item==="Future expansion"?"wide":""} key={item}>{item}{item==="Structural observations"||item==="Future expansion"?<textarea value={data.architecture[item]||""} onChange={e=>field("architecture",{...data.architecture,[item]:e.target.value})}/>:<input value={data.architecture[item]||""} onChange={e=>field("architecture",{...data.architecture,[item]:e.target.value})}/>}</label>)}</div>

      <SectionTitle number="D" title="Proposal Notes" note="Narrative fields feed directly into proposal preparation"/>
      <div className="form-grid"><label className="wide">Executive Summary<textarea value={data.proposalExecutiveSummary} onChange={e=>field("proposalExecutiveSummary",e.target.value)}/></label><label className="wide">Project Understanding<textarea value={data.proposalProjectUnderstanding} onChange={e=>field("proposalProjectUnderstanding",e.target.value)}/></label><label className="wide">Project Objectives<textarea value={data.proposalProjectObjectives} onChange={e=>field("proposalProjectObjectives",e.target.value)}/></label></div>
    </div>

    <div className="drawer-actions">{editor&&<button type="button" className="delete-visit-button" onClick={remove}>Delete visit</button>}<button type="button" onClick={()=>setEditor(undefined)}>Cancel</button><button className="primary" type="submit">{editor?"Save visit changes":"Complete visit form"}</button></div>
  </form></div></div>}</div>;
}
