export type IntelligenceInput = { enqNo:string; company:string; contact:string; city:string; projectType:string; builtUpArea:number; products?:string; bottlenecks?:string; machineCount?:number; sunSign?:string; turnoverCrore?:number; employeeBand?:string; plantCount?:number; verifiedSourceUrl?:string };

const signTraits: Record<string,{style:string;risk:string;lever:string}> = {
  Aries:{style:"Direct, concise and outcome-led",risk:"Comfortable with decisive action",lever:"Lead with speed, ownership and visible wins"}, Taurus:{style:"Practical, patient and evidence-led",risk:"Prefers proven, low-disruption change",lever:"Emphasize durability, ROI and implementation certainty"}, Gemini:{style:"Conversational and option-oriented",risk:"Open to experimentation with flexibility",lever:"Offer alternatives, visuals and short decision cycles"}, Cancer:{style:"Trust-based and context-rich",risk:"Protective of people and operational continuity",lever:"Emphasize safety, team adoption and long-term support"}, Leo:{style:"Confident, vision-led and direct",risk:"Comfortable backing visible transformation",lever:"Position the project as a category-leading facility"}, Virgo:{style:"Analytical, detailed and process-led",risk:"Low tolerance for unverified assumptions",lever:"Use data, drawings, checks and phased validation"}, Libra:{style:"Collaborative and balanced",risk:"Prefers stakeholder alignment before commitment",lever:"Show cross-functional benefits and design harmony"}, Scorpio:{style:"Focused, private and evidence-led",risk:"Takes calculated risks after deep validation",lever:"Use confidential diagnostics and measurable control"}, Sagittarius:{style:"Strategic, optimistic and future-oriented",risk:"Open to scalable investments",lever:"Lead with expansion readiness and long-term capacity"}, Capricorn:{style:"Structured, commercial and milestone-led",risk:"Disciplined, ROI-based risk appetite",lever:"Show governance, schedules and cost control"}, Aquarius:{style:"Innovative and systems-oriented",risk:"Open to differentiated technology",lever:"Highlight proprietary IP and future-ready design"}, Pisces:{style:"Empathetic, visual and purpose-led",risk:"Responds to trusted guidance",lever:"Use stories, visual concepts and guided decisions"}
};

export function buildIntelligence(input:IntelligenceInput, research?:import("./company-research").CompanyResearch){
  const project = input.projectType.toLowerCase().includes("brown") ? "Brownfield" : input.projectType.toLowerCase().includes("light") ? "Light Greenfield" : "Greenfield";
  const astro = input.sunSign && signTraits[input.sunSign] ? signTraits[input.sunSign] : null;
  const hasVerifiedSource = Boolean(input.verifiedSourceUrl);
  const turnover = Number(input.turnoverCrore || 0);
  const automaticTurnover = research?.findings.turnoverMentions[0];
  const automaticSources = research?.sources.map(source => source.url) || [];
  const hasOpenResearch = research?.status === "completed" || research?.status === "partial";
  const productDetails = research?.findings.productDetails || [];
  const company = { productsServices:input.products ? [input.products] : productDetails.length ? productDetails : [research?.findings.profileSummary || "Manufacturing portfolio requires source verification","Industrial operations and facility requirements"], officialWebsite:research?.findings.officialWebsite || input.verifiedSourceUrl || null, revenueRange:turnover ? `Approximately ₹${turnover.toLocaleString("en-IN")} crore (user-entered; verify against source)` : automaticTurnover || "No verified turnover found", coreValues:["Operational excellence","Quality and delivery reliability","Sustainable growth"], mission:"To be confirmed from an authoritative company source", foundedYear:research?.findings.foundedMentions[0] || null, milestones:research?.findings.foundedMentions || [], employeeBand:input.employeeBand || research?.findings.employeeMentions[0] || "Not verified", plantCount:input.plantCount || null, confidence:hasOpenResearch ? "Open-source results collected · human verification required" : hasVerifiedSource ? "Source supplied · human verification required" : "Preliminary", sources:[...(input.verifiedSourceUrl ? [input.verifiedSourceUrl] : []),...automaticSources] };
  const behavioral = astro ? { basis:`User-supplied sun sign: ${input.sunSign}. Astrology is non-scientific and should not drive material decisions.`, preferredCommunication:astro.style, riskTolerance:astro.risk, conversionLevers:[astro.lever,"Validate with observed business behaviour"] } : { basis:"No consented birthdate or sun sign supplied; no astrological mapping performed.", preferredCommunication:"Use observed responses and role-relevant evidence", riskTolerance:"Not inferred", conversionLevers:["Ask discovery questions","Confirm decision criteria directly"] };
  const area = input.builtUpArea || 0, rate = project === "Greenfield" ? 180 : project === "Light Greenfield" ? 120 : 85;
  const standardValue = area * rate;
  const hasResearchScale=Boolean(research?.findings.turnoverMentions.length || research?.findings.employeeMentions.length);
  const evidenceCount = [turnover > 0 || hasResearchScale, Boolean(input.employeeBand), Number(input.plantCount) > 0, hasVerifiedSource || Boolean(research?.findings.officialWebsite)].filter(Boolean).length;
  const readiness = evidenceCount >= 3 ? "Strong evidence" : evidenceCount >= 1 ? "Partial evidence" : "Insufficient evidence";
  const scopeRecommendation = area > 50000 || Number(input.plantCount) > 1 || hasResearchScale ? "Phased diagnostic, future-state layout and architecture package; validate scale evidence during discovery" : area > 0 ? "Core Gemba and future-state layout package" : "Discovery workshop before commercial scoping";
  const paymentStructure = evidenceCount >= 3 ? "Milestone billing: 20% advance, 30% layout freeze, 30% design coordination, 20% final handover" : "Begin with a paid discovery milestone; confirm scope and budget before subsequent phases";
  const researchCoverage = [
    {category:"Open knowledge",targets:["Wikipedia","Wikidata"],status:"Automatic · no key required"},
    {category:"Open news",targets:["GDELT public news index"],status:"Automatic · availability varies"},
    {category:"Company-owned",targets:["User-supplied official HTTPS website"],status:"Automatic page metadata extraction"},
    {category:"Decision maker",targets:["public professional role","company-relevant career history"],status:"Open sources only · identity verification required"}
  ];
  const proposalMarkdown = `## At-a-Glance Impact\n\n> ${input.company} can align process flow, architecture and future growth before committing capital to construction or layout changes.\n\n### Project Context\n\n| Parameter | Current intelligence |\n|---|---|\n| Project framework | ${project} |\n| Built-up area | ${area.toLocaleString("en-IN")} SqFt |\n| Major machines | ${input.machineCount || "To be confirmed"} |\n| Priority bottlenecks | ${input.bottlenecks || "WIP, material travel and future expansion to be validated during Gemba"} |\n\n## Visual Architecture & Execution\n\n- Apply Lean Factory Building© to connect process sequence with industrial architecture.\n- Use flow mapping to prevent WIP accumulation and repeated material handling.\n- Introduce Visual Countfree Stores© where inventory visibility and replenishment are constraints.\n- Assess the Passive Gravity Safety Barrier System for applicable lift-floor openings.\n- Build expansion, utilities, safety and supervision into the future-state layout.\n\n## Phase-wise Commercial Framework\n\n| Phase | Milestone | Schedule | Standard rate | Estimated value |\n|---|---|---:|---:|---:|\n| 01 | Discovery and Gemba | 1-2 weeks | Included | Included |\n| 02 | Future-state lean layout | 2-3 weeks | ₹${rate}/SqFt | ₹${(area*rate).toLocaleString("en-IN")} |\n| 03 | Architecture and coordination | Scope-based | Editable | Editable |\n| 04 | Execution support | Milestone-based | Editable | Editable |\n\n> Rates and schedules are editable planning assumptions and require commercial approval.`;
  return { schemaVersion:"1.3", generatedAt:"Jul 22, 2026, 9:00 am", lead:input, companyIntelligence:company, automaticResearch:research || null, researchCoverage, digitalFootprint:{ status:hasOpenResearch ? "Open-source professional results collected" : "No matching open professional record", matchedIdentity:null, publicCareerHighlights:research?.findings.professionalHighlights || [], observedCommunicationSignals:[], confidence:hasOpenResearch ? "Preliminary · identity verification required" : "Unavailable", privacyBoundary:"Use verified public professional information only. Exclude private life, personal wealth, family and sensitive attributes." }, enquirerBehavioralTraits:behavioral, commercialReadiness:{ evidenceStatus:readiness, standardRate:`₹${rate}/SqFt`, standardCommercialValue:standardValue, scopeRecommendation, paymentStructure, confidence:evidenceCount >= 3 ? "Medium · pending source review" : "Low · more verified evidence required", pricingGuardrail:"Never change price from inferred owner wealth. Apply the same Optispace rate card; vary only documented scope, complexity and milestones." }, proposal:{ projectFramework:project, markdown:proposalMarkdown, estimatedBasicValue:standardValue }, review:{ humanReviewRequired:true, webSourcesRequired:true, astrologyConsentRequired:true, ownerWealthPricingProhibited:true } };
}

export const socialIntelligence = {
  generatedAt:"Jul 22, 2026, 9:00 am", connectionStatus:"API connections required", channels:[{name:"Instagram",reach:0,growth:0,engagement:0},{name:"LinkedIn",reach:0,growth:0,engagement:0},{name:"Facebook",reach:0,growth:0,engagement:0},{name:"YouTube",reach:0,growth:0,engagement:0}],
  recommendations:[
    {format:"Lean factory transformation reel",hook:"Where is hidden travel costing your factory every shift?",frequency:"2 per week",channels:"Instagram, LinkedIn, YouTube Shorts",tags:"#LeanFactory #IndustrialArchitecture #MaterialFlow"},
    {format:"Drafting time-lapse",hook:"From process flow to buildable industrial architecture",frequency:"1 per week",channels:"LinkedIn, Instagram, YouTube",tags:"#FactoryDesign #Gemba #Architecture"},
    {format:"WIP diagnostic carousel",hook:"Five layout signals that predict WIP accumulation",frequency:"1 per week",channels:"LinkedIn, Facebook, Instagram",tags:"#WIP #LeanManufacturing #LFB"},
    {format:"Founder insight video",hook:"Build the process first, then the building",frequency:"2 per month",channels:"YouTube, LinkedIn",tags:"#LeanLeadership #Optispace #Manufacturing"}
  ]
};
